### ISSUE TITLE
compability with protobuffer flatc?

### ISSUE THREAD

**Issue by navigator117** [dvidelabs/flatcc#65] opened 2017-11-22 10:39 UTC
same schema file as input,
for client, I use FlatBuffers's flatc to generate javascript proto defination and sender.
for server, I use flatcc to generate proto handler.
when I verify the recv data in server use verify_as_root API,
It says:  runtime: buffer header not aligned!

**Comment by mikkelfj** [comment] 2017-11-22 10:43
I need a schema and a buffer in order to investigate.

You might have a size prefixed buffer that you do not handle correctly, or you might just need to place the buffer in aligned memory. You can use aligned_alloc for this, if you align to 256 bytes you should be safe.

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/paligned_alloc.h

**Comment by navigator117** [comment] 2017-11-22 11:59
but the data which was send from client, it's javascript proto was create by flatc, there were no align API at there like C.

**Comment by mikkelfj** [comment] 2017-11-22 12:03
The verifier considers how the buffer is placed in memory. This must be done on the receiving end because even if Java correctly creates an aligned buffer it can still be stored unaligned after transport over the network. Intel architecture is not very sensitive to correct alignment, but the verifier is strict about this.

**Comment by mikkelfj** [comment] 2017-11-22 12:08
Also note a regression in the verifier in latest release, that has been fixed on master. Not sure this is the issue, but worth noting.

https://github.com/dvidelabs/flatcc/issues/60

**Comment by navigator117** [comment] 2017-11-23 02:41
I just supply received data & length from socket to *_verify_root.  If I didn't verify, the protocol data were parsing successful.

**Comment by mikkelfj** [comment] 2017-11-23 06:43
If you allocate a block of memory and copy the buffer to at start address that is a multiple of 256 then the verifier should succeed. Less alignment may be enough, but it depends on the schema. aligned_alloc provides such memory.

Maybe it would be useful to have an option where the verifier only verifies relative to the buffer start and the absolute memory in case you don't care, but on some systems that could lead to a CPU exception when reading the buffer.

**Comment by mikkelfj** [comment] 2017-11-23 06:45
See also the flatc_compat test which reads a binary buffer and verifies it:

https://github.com/dvidelabs/flatcc/blob/master/test/flatc_compat/flatc_compat.c#L179-L208

**Comment by navigator117** [comment] 2017-11-23 09:41
maybe the option should add. data may come with pack header, for efficiency, the header was copied with data to buffer, and the data is read at an offset position. now, the data is not start at aligned buffer start.

**Comment by navigator117** [comment] 2017-11-23 09:56
/*
 0 1 2 3 4 5 6 7 8 9 A B C D E F 0 1 2 3 4 5 6 7 8 9 A B C D E F
+-+-+-+-+-------+-+-------------+-------------------------------+
|F|R|R|R| opcode|M| Payload len |    Extended payload length    |
|I|S|S|S|  (4)  |A|     (7)     |             (16/64)           |
|N|V|V|V|       |S|             |   (if payload len==126/127)   |
| |1|2|3|       |K|             |                               |
+-+-+-+-+-------+-+-------------+ - - - - - - - - - - - - - - - +
|     Extended payload length continued, if payload len == 127  |
+ - - - - - - - - - - - - - - - +-------------------------------+
|                               |Masking-key, if MASK set to 1  |
+-------------------------------+-------------------------------+
| Masking-key (continued)       |          Payload Data         |
+-------------------------------- - - - - - - - - - - - - - - - +
:                     Payload Data continued ...                :
+ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
|                     Payload Data continued ...                |
+---------------------------------------------------------------+
*/
struct _WEBSOCK_PROTO_HEADER
{
    uint8_t _opcode:4;                                                                                                                                                                                                                                                                                                            
    uint8_t _rsv3:1;                                                                                                                                                                                                                                                                                                              
    uint8_t _rsv2:1;                                                                                                                                                                                                                                                                                                              
    uint8_t _rsv1:1;                                                                                                                                                                                                                                                                                                              
    uint8_t _fin:1;                                                                                                                                                                                                                                                                                                               
    uint8_t _length:7;                                                                                                                                                                                                                                                                                                            
    uint8_t _mask:1;                                                                                                                                                                                                                                                                                                              
    union {
        struct {
            uint8_t _data[0];                                                                                                                                                                                                                                                                                                     
        } _len7_without_key;                                                                                                                                                                                                                                                                                                      
        struct {
            uint8_t _keys[4];                                                                                                                                                                                                                                                                                                     
            uint8_t _data[0];                                                                                                                                                                                                                                                                                                     
        } _len7_with_key;                                                                                                                                                                                                                                                                                                         
        struct {
            uint16_t _length;                                                                                                                                                                                                                                                                                                     
            uint8_t _data[0];                                                                                                                                                                                                                                                                                                     
        } _len16_without_key;                                                                                                                                                                                                                                                                                                     
        struct {
            uint16_t _length;                                                                                                                                                                                                                                                                                                     
            uint8_t _keys[4];                                                                                                                                                                                                                                                                                                     
            uint8_t _data[0];                                                                                                                                                                                                                                                                                                     
        } _len16_with_key;                                                                                                                                                                                                                                                                                                        
        struct {
            uint64_t _length;                                                                                                                                                                                                                                                                                                     
            uint8_t  _data[0];                                                                                                                                                                                                                                                                                                    
        } _len64_without_key;                                                                                                                                                                                                                                                                                                     
        struct {
            uint64_t _length;                                                                                                                                                                                                                                                                                                     
            uint8_t  _keys[4];                                                                                                                                                                                                                                                                                                    
            uint8_t  _data[0];                                                                                                                                                                                                                                                                                                    
        } _len64_with_key;                                                                                                                                                                                                                                                                                                        
    } _u;                                                                                                                                                                                                                                                                                                                         
};                                                                                                                                                                                                                                                                                                                                
typedef struct _WEBSOCK_PROTO_HEADER WEBSOCK_PROTO_HEADER;

as your saw, websocket data may recv with this header to an aligned buffer, and the data offset is not at fixed position due to different length value (8/16/64 bits value).

**Comment by mikkelfj** [comment] 2017-11-24 08:41
It appears you only need 8 byte alignment which malloc usually provides. Please try to copy the buffer and verify so we can rule out any other issues, just for testing.

You cannot verify in-place in the socket buffer as is.

**Closed** 2017-12-04 08:27 UTC
Labels: question

**Comment by mikkelfj** [comment] 2017-12-23 17:33
@navigator117 I just looked at the verifier source. You say you get a "buffer header not aligned!" error.

The verifier actually checks alignment relative to the buffer start and not to the actual memory location. But the buffer start must still be aligned to 4 bytes because otherwise it is not safe to read the data needed to verify the buffer. It would be possible to remove this limitation by using unaligned reads, and I will consider supporting this in a future release.

**Comment by navigator117** [comment] 2017-12-26 03:29
That's great! I have tried copy and verify without question. Can't wait for your new release with this enhencement. BTW, I found a site https://scan.coverity.com for github opensource code static analysis, maybe help to reduce your workload :)

**Comment by mikkelfj** [comment] 2017-12-26 15:39
Thanks for the update. It is not very easy to support unaligned verification because you must choose one of the following options, each with its own trade-off:

- add a runtime option to just not fail on unaligned header. But then the verifier will crash on some systems.
- use flatcc_unaligned_read_... internally which is safe and is also sort of easy to add because the portable library has it, but then verifier will be slow on some systems.
- detect if the platform natively supports unaligned access (is defined in a portable header) and use it at no performance cost, and otherwise fail, but that is kind of a hack because the user code might suddenly fail to verify when moved to a different platform.
- add a global FLATCC compile time flag to use unaligned access. If enabled both the verifier and all other flatbuffer operations are safe to use in unaligned buffers, and will be fast or slow depending on the system. This is not too difficult because all flatcc read operations go through some access functions that can be redefined with a flag (similar to how FLATCC can be compiled to use big endian natively).

I think the last option is the best and it also avoids adding even more verify functions - there are a lot already (with type hash, with identifier, etc.). The downside is that it won't work with standard package distributions but it is not difficult to include the runtime files directly in a project.

As to coverage: Another user added the following option to the CMake configuration - but I haven't really been using it. It uses clang's/gcc's native coverage tool:

```
# Use with debug build with testing enabled only. Enables generation
# of coverage information during build and run. Adds target "coverage"
# which collects data and makes HTML report in build directory
option(FLATCC_COVERAGE "enable coverage" OFF)
```
