### ISSUE TITLE
Floats on big-endian systems

### ISSUE THREAD

**Issue by joeygannon** [dvidelabs/flatcc#125] opened 2019-08-15 23:08 UTC
I've been seeing some peculiar issues with using floats on a big-endian system, so I've created a minimal example to reproduce it and hopefully gain some insight. First, I have this simple schema:
```
table Message
{
    foo: uint16;
    bar: float32;
}

root_type Message;
```
Then I wrote a C program to populate foo and bar, print the byte representation of bar, and extract the direct buffer and print its bytes:
```
#include <stdio.h>

#include "flatcc/flatcc_builder.h"
#include "message_builder.h"

int main()
{
    size_t idx = 0;
    size_t buffer_size = 0;
    uint8_t* buffer = 0;
    uint16_t foo = 0xBEEF;
    float bar = 1234.0;
    
    flatcc_builder_t builder;
    flatcc_builder_init(&builder);

    Message_start_as_root(&builder);
    Message_foo_add(&builder, foo);
    Message_bar_add(&builder, bar);
    Message_end_as_root(&builder);

    printf("                                    ");
    for(idx = 0; idx < sizeof(float); ++idx)
    {
        printf("%02x ", ((uint8_t*)&bar)[idx]);
    }
    printf("\n");

    buffer = flatcc_builder_get_direct_buffer(&builder, &buffer_size);
    for(idx = 0; idx < buffer_size; ++idx)
    {
        printf("%02x ", buffer[idx]);
    }
    printf("\n");

    flatcc_builder_clear(&builder);

    return 0;   
}
```
When I run this on my laptop, it works as I'd expect:
```
$ uname -a
Linux pajamas 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ make
../flatcc/bin/flatcc -a message.fbs
cc -I. -I../flatcc/include/ -o simple simple.c -L../flatcc/lib/ -lflatccrt
$ ./simple 
                                    00 40 9a 44 
04 00 00 00 f4 ff ff ff ef be 00 00 00 40 9a 44 08 00 0c 00 04 00 08 00
```
You can see the BEEF, you can see the float, everything is good. When I run it on my big-endian system, the float has gotten mangled:
```
$ uname -a
Linux lubuntu 4.4.0-31-powerpc-smp #50~14.04.1-Ubuntu SMP Wed Jul 13 01:13:48 UTC 2016 ppc ppc ppc GNU/Linux
$ make
../flatcc/bin/flatcc -a message.fbs
cc -I. -I../flatcc/include/ -o simple simple.c -L../flatcc/lib/ -lflatccrt
$ ./simple 
                                    44 9a 40 00 
04 00 00 00 f4 ff ff ff ef be 00 00 00 80 00 04 08 00 0c 00 04 00 08 00
```
It has packed the integer in little-endian order, which tells me it's detecting my system endianness correctly, but I have no idea what's going on with the float; it's not backwards, it's just completely wrong. Any tips?

**Comment by joeygannon** [comment] 2019-08-16 15:12
For what it's worth, the decoding side doesn't fare any better:
```
#include <stdio.h>

#include "message_builder.h"

int main()
{
    uint8_t buffer[24] = {0x04, 0x00, 0x00, 0x00, 0xf4, 0xff, 0xff, 0xff, 0xef, 0xbe, 0x00, 0x00,
                          0x00, 0x40, 0x9a, 0x44, 0x08, 0x00, 0x0c, 0x00, 0x04, 0x00, 0x08, 0x00};
    uint16_t foo;
    float bar;

    Message_table_t message;
    message = Message_as_root(buffer);
    if (!message)
    {
        fprintf(stderr, "Error parsing message!\n");
        return -1;
    }

    foo = Message_foo(message);
    bar = Message_bar(message);

    printf("%04x %f\n", foo, bar);

    return 0;   
}
```
Prints `beef 1234.000000` on x86_64 and `beef 0.000000` on PowerPC.

**Comment by mikkelfj** [comment] 2019-08-16 15:33
This indeed does not look right. If you are willing to work with me, we can try track down the issue, but I do not have access to hardware to do this on my own.

Big endian testing is limited due to lack of access to hardware. Last time it was thoroughly tested was release 0.4.0 thanks to user willing to run the tests and help fixing issues. This suggests that it is likely that floating point encoding was working at the time because the monster_test.c file passed. Subsequently nothing has been added that would actively break big endian and some users have been working with big endian systems.

**Comment by mikkelfj** [comment] 2019-08-16 16:23
The fact that the data is garbled reading is important. It (sort of) rules out that the buffer is written incorrectly due to circumstances beyond float encoding.

I suspect the union cast might be an issue.

All flatcc types, and also structs, has a cast_to/from_pe function that does endian conversion. 

Reading scalar fields from a table involves first locating a pointer in the buffer, then reading the correct amount of bytes as an unsigned integer of a specific size, then optionally byteswapping the integer. And finally the unsigned integer is cast the expected type. E.g. a signed integer or a float. There are many ways to this cast, an no ideal way to do it.

The union cast is not strictly valid C but moderately better that doing a pointer cast which is definitely not standard, although it often works. These days memcpy is considered the best approach, but not long ago that was very inefficient, and still can be on some platforms.

See
__flatcc_define_real_accessors_impl
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_accessors.h

You could try overriding the contents of this file doing a memcpy type conversion. You could also try to disable optimisations, or you could try a pointer cast. If you need input on how to do this, let me know.

Take for example float_cast_from_pe which takes a floating point value encoding in the protocol native format (which is always little endian for flatbuffers on all platforms). It casts the value to the host platform encoding which is big endian in you case. The actual byteswapping is done  using le32toh(u) where le32toh is defined in the low level endian support framework in the portable library. This function likely works, at least we know that le16toh works for your 0XBEEF value.

Explanation of macro:

```
#define __flatcc_define_real_accessors_impl(N, T, W, E)                     \
union __ ## N ## _cast { T v; uint ## W ## _t u; };                         \
static inline T N ## _cast_from_pe(T v)                                     \
{ union __ ## N ## _cast x;                                                 \
  x.v = v; x.u = E ## W ## toh(x.u); return x.v; }                          \
```

N is the type name, e.g. "float", T is the actual type, also "float" (as opposed to int32 vs int32_t), W is the width (sizeof(float)*8=32), and E is the endianness of the protocol with is always "le" for standard flatbuffers. For reference pe means protocol endian because the protocol might be little or big endian. Flatbuffers protocol is le, so `union_float_from_pe` means casting from little endian to host.

Expanding the function you get:

static inline float float_cast_from_pe(float v)

The other macros works in a similar fashion.

**Comment by mikkelfj** [comment] 2019-08-16 16:32
Going a bit deeper, the common_reader code has a macro to define the actual function you call to read a field:

```
#define __flatbuffers_read_scalar_at_byteoffset(N, p, o) N ## _read_from_pe((uint8_t *)(p) + (o))
...
static inline T N ## _ ## NK ## _get(N ## _table_t t__tmp)\
{ __flatbuffers_read_vt(ID, offset__tmp, t__tmp)\
  return offset__tmp ? __flatbuffers_read_scalar_at_byteoffset(TK, t__tmp, offset__tmp) : V;\
}\
```

We see that float_read_from_pe(pointer, offset) is being called. Going back to the previously mentioned access.h file, we find

```
static inline T N ## _read_from_pe(const void *p)                           \
{ return N ## _cast_from_pe(*(T *)p); }                                     \
```
And finally we get a call the float_cast_from_pe function.

(all this optimizes heavily).

I don't know if this is the root cause, but it is worth investigating.

If you keep the schema very simple, you can simple comment out the macro and replace with an actual named function like `float_read_from_pe` and `int16_read_from_pe`. If the schema is complex you will miss the functions for other types.

Note that the pointer cast `*(T *)` could be something that could confuse a compiler if the union cast does not.

**Comment by joeygannon** [comment] 2019-08-16 16:53
I think I'm following what you're saying as far as redoing the accessor using memcpy, I will look into that and see what I can come up with.

Here's some other info that may or may not be interesting, that I came across while you were typing. You'd mentioned that v0.4.0 was the last release to be thoroughly tested on a big-endian system, so I checked out that tag and built it. It was failing when trying to [include mm_alloc.h here](https://github.com/dvidelabs/flatcc/blob/v0.4.0/include/flatcc/portable/paligned_alloc.h#L56), which is apparently not provided on this platform. I pulled in the version of `paligned_alloc.h` from the tip instead, and it built fine. As you'd expect, I also had to change the data types in my schema to `short` and `float` respectively. After making these two changes, I'm still seeing the same output from my test programs.

My takeaway from this is, maybe it's not an endianness issue at all? Maybe this will trigger some more ideas for you. In the meantime, I'll dig into what you've written. Thank you very much for your prompt and well-considered replies. :smile:

**Comment by mikkelfj** [comment] 2019-08-16 17:06
Try this

```c
#include <stdint.h>
#include <stdio.h>

#include <flatcc/portable/pendian.h>
#include <flatcc/portable/pstdalign.h>

union __float_cast { float v; uint32_t u; };

static inline float float_cast_from_pe(float v)
{
    union __float_cast x;
    x.v = v; x.u = le32toh(x.u);
    return x.v;
}

static inline float float_read_from_pe(const void *p)
{
    return float_cast_from_pe(*(float *)p);
}  

static inline float read_float(void *p, size_t offset)
{
    return float_read_from_pe((uint8_t *)p + offset);
}


int main()
{

    /* NOTE: alignas, the buffer must be aligned. */
    alignas(uint32_t) uint8_t buffer[24] = {
            0x04, 0x00, 0x00, 0x00, 0xf4, 0xff, 0xff, 0xff,
            0xef, 0xbe, 0x00, 0x00, 0x00, 0x40, 0x9a, 0x44,
            0x08, 0x00, 0x0c, 0x00, 0x04, 0x00, 0x08, 0x00
    };
    
    float bar;

    bar = read_float(buffer, 12);

    printf("bar: %f\n", bar);

    return 0;   
}
```

**Comment by mikkelfj** [comment] 2019-08-16 17:22
The 0.4.0 was tested in IAX with an IBM compiler.
Naturally some issues have been fixed since 0.4.0 as you have discovered.

As you suggest it is probably not directly an endian issue, but probably part of the conversion logic just above. My test code should make it easier to reproduce and change things.

Please be aware that that buffers must be aligned - the example you provided was not - it is very very common mistake in these situations, and normally it works fine. But the verifier will complain and some systems, e.g. WebAssembly, will fail. I don't think this is a root cause, but it could still affect results if the compiler is confused.

**Comment by joeygannon** [comment] 2019-08-16 17:33
It's printing `bar: 0.000000`

**Comment by mikkelfj** [comment] 2019-08-16 17:34
That's great. This mean we can reproduce. Now on to fixing ...

**Comment by joeygannon** [comment] 2019-08-16 18:02
This is... surprising, to me at least. I instrumented your function as so:
```
static inline float float_read_from_pe(const void *p)
{
    float* x = (float*)p;
    printf("%08x\n", *((uint32_t*)x));
    float v = *x;
    printf("%08x\n", *((uint32_t*)(&v)));
    return float_cast_from_pe(*(float *)p);
}
```
It's printing:
```
00409a44
00800004
bar: 0.000000
```
So dereferencing the float* is clearly not doing what I'd expect...

**Comment by mikkelfj** [comment] 2019-08-16 18:12
```c
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>

#include <flatcc/portable/pendian.h>
#include <flatcc/portable/pstdalign.h>

union __float_cast { float v; uint32_t u; };

static inline float float_cast_from_pe(float v)
{
    union __float_cast x;
    x.v = v; x.u = le32toh(x.u);
    return x.v;
}

static inline float float_read_from_pe2(const void *p)
{
    uint32_t u;
    float f;

    assert(sizeof(u) == sizeof(f));

    memcpy(&u, p, sizeof(u));
    u = le32toh(u);
    memcpy(&f, &u, sizeof(f));
    return f;
}

static inline float float_read_from_pe(const void *p)
{
    return float_cast_from_pe(*(float *)p);
}  

static inline float read_float(void *p, size_t offset)
{
    return float_read_from_pe2((uint8_t *)p + offset);
}

int main()
{

    /* NOTE: alignas, the buffer must be aligned. */
    alignas(uint32_t) uint8_t buffer[24] = {
            0x04, 0x00, 0x00, 0x00, 0xf4, 0xff, 0xff, 0xff,
            0xef, 0xbe, 0x00, 0x00, 0x00, 0x40, 0x9a, 0x44,
            0x08, 0x00, 0x0c, 0x00, 0x04, 0x00, 0x08, 0x00
    };
    
    float bar;

    bar = read_float(buffer, 12);

    printf("bar: %f\n", bar);

    return 0;   
}
```

**Comment by joeygannon** [comment] 2019-08-16 18:22
Hey, that works! :open_mouth:
`bar: 1234.000000`

**Comment by mikkelfj** [comment] 2019-08-16 18:24
How many memcpy's can we remove, where, performance, asm dump?

I'm hesitant to just rip out everything to fix powerpc since it could perform badly on some systems even if modern clang is doing this efficiently.

We'd also need to run the full monster_test to check for other issues otherwise it is pointless to fix.

**Comment by mikkelfj** [comment] 2019-08-16 18:38
If we fix this, I'll make a release first so as to not break the world just before a release.

**Comment by mikkelfj** [comment] 2019-08-16 18:46
BTW: I'm curious about the builder side. It seems that the fix needs to be in the common reader and the builder probably uses the accessors same as the reader.

From common_builder:
```c
#define __flatbuffers_define_scalar_primitives(NS, N, T)\
static inline T *N ## _from_pe(T *p) { return __ ## NS ## from_pe(p, N); }\
static inline T *N ## _to_pe(T *p) { return __ ## NS ## to_pe(p, N); }\
static inline T *N ## _copy(T *p, const T *p2) { *p = *p2; return p; }\
static inline T *N ## _copy_from_pe(T *p, const T *p2)\
{ return __ ## NS ## copy_from_pe(p, p2, N); }\
static inline T *N ## _copy_to_pe(T *p, const T *p2) \
{ return __ ## NS ## copy_to_pe(p, p2, N); }\
static inline T *N ## _assign(T *p, const T v0) { *p = v0; return p; }\
static inline T *N ## _assign_from_pe(T *p, T v0)\
{ *p = N ## _cast_from_pe(v0); return p; }\
static inline T *N ## _assign_to_pe(T *p, T v0)\
{ *p = N ## _cast_to_pe(v0); return p; }
#define __flatbuffers_build_scalar(NS, N, T)\
__ ## NS ## define_scalar_primitives(NS, N, T)\
__ ## NS ## define_fixed_array_primitives(NS, N, T)\
__ ## NS ## build_vector(NS, N, T, sizeof(T), sizeof(T))

...

#define __flatbuffers_build_scalar_field(ID, NS, N, TN, T, S, A, V, TT)\
static inline int N ## _add(NS ## builder_t *B, const T v)\
{ T *_p; if (v == V) return 0; if (!(_p = (T *)flatcc_builder_table_add(B, ID, S, A))) return -1;\
  TN ## _assign_to_pe(_p, v); return 0; }\

```

notably 

```c
static inline T *N ## _assign_to_pe(T *p, T v0)\
{ *p = N ## _cast_to_pe(v0); return p; }
```

**Comment by joeygannon** [comment] 2019-08-16 18:46
I certainly wouldn't encourage you to make big sweeping changes to handle my incredibly uncommon use case. The good news is it looks like I don't need either of the memcpy calls, it just needs the bytes to be in the right order before they go into the float. This implementation is working for me:
```
static inline float float_read_from_pe2(const void *p)
{
    uint32_t u;
    float f;

    assert(sizeof(u) == sizeof(f));

    u = *(uint32_t*)p;
    u = le32toh(u);
    f = *(float*)&u;
    return f;
}
```

**Comment by mikkelfj** [comment] 2019-08-16 18:50
Could you rewrite that with the float cast function modified to take a uint32 pointer as input so you avoid `*(float*)&u`?

I was actually surprised that I didn't do that already when I first went through the code.

**Comment by mikkelfj** [comment] 2019-08-16 18:55
I think I'll but this a bit on the back burner and get back to with a proper redesign after a release. 

Would you be willing to run tests then, or are you just passing through on this platform for now?

I'm considering if I would prefer memcpy over *(float *) and union casts because it is the only documented valid method and it is fast on modern systems, and probably fast enough on other systems.

Regardless, it is good to know of all methods that work, but `*(float *)` seems to only work by accident in your case.

**Comment by joeygannon** [comment] 2019-08-16 19:18
I'm not sure if this is what you meant, but I rewrote it to this:
```
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>

#include <flatcc/portable/pendian.h>
#include <flatcc/portable/pstdalign.h>

union __float_cast { float v; uint32_t u; };

static inline float float_cast_from_pe(uint32_t* u)
{
    union __float_cast x;
    x.u = le32toh(*u);
    return x.v;
}

static inline float float_read_from_pe(const void *p)
{
    return float_cast_from_pe((uint32_t*)p);
}  

static inline float read_float(void *p, size_t offset)
{
    return float_read_from_pe((uint8_t *)p + offset);
}

int main()
{

    /* NOTE: alignas, the buffer must be aligned. */
    alignas(uint32_t) uint8_t buffer[24] = {
            0x04, 0x00, 0x00, 0x00, 0xf4, 0xff, 0xff, 0xff,
            0xef, 0xbe, 0x00, 0x00, 0x00, 0x40, 0x9a, 0x44,
            0x08, 0x00, 0x0c, 0x00, 0x04, 0x00, 0x08, 0x00
    };
    
    float bar;

    bar = read_float(buffer, 12);

    printf("bar: %f\n", bar);

    return 0;   
}
```
That also works, again seemingly because the bytes are in the right order before they become a float.

I'm developing a safety-critical system on a big-endian platform that is not currently available to me, so I chose PowerPC in the interim to do some stress testing and investigate whether the endianness behavior performs as advertised. It's distinctly possible that it will just work as-is on my target, but you can imagine this gave me reason to worry that it won't. What's your expected timeframe for a redesign?

**Comment by mikkelfj** [comment] 2019-08-16 19:33
If you have an important use case I can expedite things, but I won't promise anything before a week or two. In this case I will probably do something along your last change using a float cast because it is has minimal impact on current behaviour. It will be breaking change on some low level cast methods, but I think that is fine.

**Comment by mikkelfj** [comment] 2019-08-16 19:34
flatcc is intended to work on nearly all platforms, not just the major platforms. Otherwise there is no point in having a portable format.

**Comment by mikkelfj** [comment] 2019-08-16 19:53
For reference, Jens Gustedt says union casts are fine in C, even if they are not in C++.

https://gustedt.wordpress.com/2014/04/02/dont-use-casts-i/

**Comment by mikkelfj** [comment] 2019-08-16 22:37
I added a new branch `befloat` that you can try out for now.

Benchmarks suggest about same performance on MacOS clang little endian.
It uses memcpy. I removed the cast_float etc. functions because the interface was fundamentally broken and replaced it with higher level read/write functions. I then replaced a lot of calls to cast functions with these read / write functions. The read/write interface already existed but wasn't used everywhere.

The flatcc_accessors.h file could use some clean up because int and float are now the same implementation. There are a lot of semaingly meaningless chains of macro calls - but without these macro expansions breaks - it is a black art.

**Comment by mikkelfj** [comment] 2019-08-17 06:24
https://github.com/dvidelabs/flatcc/tree/befloat

**Comment by mikkelfj** [comment] 2019-08-17 06:58
Not all compilers work equally well with memcpy - the change I made uses memcpy for both float and ints on both little and big endian. I'm not sure that is right even if it works on the latest main stream. But at least there is a (hopefully) working branch.

https://gcc.godbolt.org/z/26Pim-

```
#include <stdint.h>
#include <string.h>

float sum_float(const char *buf, size_t size)
{
    float sum = 0;
    for(size_t i = 0; i < size; i += sizeof(uint32_t))
    {
        float v;
        memcpy(&v, &buf[i], sizeof(uint32_t));
        sum += v;
    }
    return sum;
}

float sum_float2(const char *buf, size_t size)
{
    const float* data=(const float*)buf;
    float sum = 0;
    for(size_t i = 0; i < size; ++i)
        sum += data[i];
    return sum;
}
```

**Comment by mikkelfj** [comment] 2019-08-17 11:18
befloat branch now only uses memcpy for floats.

flatcc 0.6.0 has been released: https://github.com/dvidelabs/flatcc/releases/tag/v0.6.0

I can merge befloat to master once I get some confirmation. There are two parts:

1. Interface change: all "other" code now uses read/write_pe instead of calling cast_to/from_pe directly. This interface change will remain. The read/write interface existed but wasn't used everywhere.
2. The flatcc_accessors.h file is probably OK as is in befloat, but if not, this is the only place to change. This means it can be customized once the interface change has been effected.

**Comment by joeygannon** [comment] 2019-08-19 14:58
Thanks so much for following up on this so quickly! I've built the `befloat` branch on my ppc setup, and all 21 tests in your suite now pass, as does the toy example I originally posted. I'm feeling a lot more confident in using flatcc in my project going forward. :smile: If there's any other testing I can do to be helpful, feel free to reach out.

**Comment by mikkelfj** [comment] 2019-08-19 15:26
That's good to hear. The master branch has already merged half the changes already such the remaining difference is in the flatcc_accessors.h file only. That minimizes the impact on current code while it provides ppc uses a simple way to replace one file until a proper implementation is chosen:

I will probably merge befloat to master, but I'm still not 100% convinced because some compilers work poorly with memcpy.

**Comment by mikkelfj** [comment] 2020-02-21 12:46
@joeygannon I'm not sure I'm ready to move everything to memcpy just yet. Is the solution on the master branch sufficient for your needs, or is more needed?

**Comment by mikkelfj** [comment] 2020-03-11 08:31
I closing this, assuming the master branch is sufficient. I don't test material to indicate otherwise. Feel free to reopen if the problem persists.

**Closed by mikkelfj** 2020-03-11 08:31 UTC
Labels: bug
