### ISSUE TITLE
Incorrect frame allocation for deeply nested builder operations (was Assert hit with clang 3.4.1 on 32bits plateforms)

### ISSUE THREAD

**Issue by epouponstormshield** [dvidelabs/flatcc#41] opened 2017-05-12 08:42 UTC
Hello,

We hit an annoying issue using clang 3.4.1 on FreeBSD 10.3, but only on 32bits systems (it works fine with the same version of clang on 64bits systems)

Please find attached a schema and a C code sample that triggers the problem.

Steps to reproduce:

> $ flatcc my_ns.fbs -cwv --outfile=./my_ns.fbs.h
> 
> $ cc -Wall -std=c99 test.c -o test -Iflatcc-0.4.1//include/ -DFLATCC_REFLECTION=0 -DFLATCC_PORTABLE flatcc-0.4.1/lib/libflatccrt.a
> 
> $ ./test 
> Assertion failed: ((B->frame[0].type) == flatcc_builder_table), function flatcc_builder_check_required, file <...>/flatcc-0.4.1/src/runtime/builder.c, line 1242.
> Abort trap (core dumped)
> 

If I add only "TEST NAME" or "TEST VALUE", it works as expected.
Maybe I do something wrong, but it is strange since it works fine on 64bit arch?

Regards

[example.zip](https://github.com/dvidelabs/flatcc/files/995506/example.zip)

**Comment by mikkelfj** [comment] 2017-05-12 09:06
I will have a look - I need a VM to set up 32-bit - meanwhile it might be as simple as incorrect use of API, but if so, the same error should appear on 64-bits.

The following functions can be used during buffer construction to print a trace of how the frame is being built. It tracks the nesting level and the frame type. lldb can also be used.

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_builder.h#L537
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_builder.h#L801

**Comment by mikkelfj** [comment] 2017-05-12 09:23
As a preliminary explanation - but we still need to figure out the difference for 32-bits:

info_push_start means that you start the member table of the vector. Since info is a vector status tables, the status table has already been opened, so calling status_start is not needed, nor correct.

```
	my_ns_infovec_info_push_start(&builder);

	my_ns_info_status_start(&builder);
```

This is later followed by this code which reverts the order of push_end and status end:
```
		my_ns_info_status_push_end(&builder);
	my_ns_info_status_end(&builder);
```
If you switched the above statements, you would end the inner status and it would just be garbage, and the push_end would add an empty status object.

NOTE: this is from a quick read of the source, and I do not recall all details of the API, so I might be mistaken - but this is what pops out right now. If you can help identify why 32-bit behaves differently it would be a great help - certainly something I need to figure out.

Also, the project could need better documentation - mkdocs with several examples - if anyone feels like taking this up, it might help prevent such issues in the future.

**Comment by mikkelfj** [comment] 2017-05-12 09:33
The API is flexible but this causes som confusion:

`vector_start, table_start, table_add,, ..., ref = table_end, vector_push(ref), vector_end`

or
`vector_start, vector_push_start, table_add,..., vector_push_end, ..., vector_end`

**Comment by epouponstormshield** [comment] 2017-05-12 10:00
Thanks for your support!

it seems we correctly use the second mentioned version?

I added some verbose using the functions you suggested.
Here is what I get (the values are printed just after each call)

> flatcc_builder_init(&builder) - Lvl = 0 - Type = 0
> my_ns_infovec_start_as_root(&builder) - Lvl = 2 - Type = 3
> my_ns_infovec_info_start(&builder) - Lvl = 3 - Type = 5
> my_ns_infovec_info_push_start(&builder) - Lvl = 4 - Type = 3
> my_ns_info_status_start(&builder) - Lvl = 5 - Type = 5
> my_ns_info_status_push_start(&builder) - Lvl = 6 - Type = 3
> my_ns_status_value_add(&builder, 50) - Lvl = 6 - Type = 3
> my_ns_status_attr_infos_start(&builder) - Lvl = 7 - Type = 5
> my_ns_status_attr_infos_push_start(&builder) - Lvl = 8 - Type = 3
> my_ns_attr_infos_name_add(&builder, flatbuffers_string_create_str(&builder, "TEST NAME")) - Lvl = 8 - Type = 3
> my_ns_attr_infos_value_add(&builder, flatbuffers_string_create_str(&builder, "TEST VALUE")) - Lvl = 8 - Type = 65535
> Assertion failed: ((B->frame[0].type) == flatcc_builder_table), function flatcc_builder_check_required, file <...>/flatcc-0.4.1/src/runtime/builder.c, line 1242.
> Abort trap (core dumped)

my_ns_status_attr_infos_push_end(&builder) makes the assertion

Removing "TEST NAME" gives this result:
> flatcc_builder_init(&builder) - Lvl = 0 - Type = 0
> my_ns_infovec_start_as_root(&builder) - Lvl = 2 - Type = 3
> my_ns_infovec_info_start(&builder) - Lvl = 3 - Type = 5
> my_ns_infovec_info_push_start(&builder) - Lvl = 4 - Type = 3
> my_ns_info_status_start(&builder) - Lvl = 5 - Type = 5
> my_ns_info_status_push_start(&builder) - Lvl = 6 - Type = 3
> my_ns_status_value_add(&builder, 50) - Lvl = 6 - Type = 3
> my_ns_status_attr_infos_start(&builder) - Lvl = 7 - Type = 5
> my_ns_status_attr_infos_push_start(&builder) - Lvl = 8 - Type = 3
> my_ns_attr_infos_value_add(&builder, flatbuffers_string_create_str(&builder, "TEST VALUE")) - Lvl = 8 - Type = 3
> my_ns_status_attr_infos_push_end(&builder) - Lvl = 7 - Type = 5
> my_ns_status_attr_infos_end(&builder) - Lvl = 6 - Type = 3
> my_ns_info_status_push_end(&builder) - Lvl = 5 - Type = 5
> my_ns_info_status_end(&builder) - Lvl = 4 - Type = 3
> my_ns_infovec_info_push_end(&builder) - Lvl = 3 - Type = 5
> my_ns_infovec_info_end(&builder) - Lvl = 2 - Type = 3
> my_ns_info_end_as_root(&builder) - Lvl = 0 - Type = 0

Does that help? Maybe there is something wrong woth the use of flatbuffers_string_create_str?

**Comment by mikkelfj** [comment] 2017-05-12 10:31
Added numbers to frame types to help make sense
enum flatcc_builder_type {
    flatcc_builder_empty = 0,
    flatcc_builder_buffer = 1,
    flatcc_builder_struct = 2,
    flatcc_builder_table = 3,
    flatcc_builder_vector = 4,
    flatcc_builder_offset_vector = 5,
    flatcc_builder_string = 6
};

**Comment by mikkelfj** [comment] 2017-05-12 10:53
[1] `my_ns_infovec_start_as_root(&builder) - Lvl = 2 - Type = 3`

now you are at an open root table. Lvl is 2 because you have an open buffer and an open table.

[2] `my_ns_infovec_info_start(&builder) - Lvl = 3 - Type = 5`

Now you have opened a table vector so the we have one more level and type is offset vector as 
expected.

[3] `my_ns_infovec_info_push_start(&builder) - Lvl = 4 - Type = 3`

And now we also have a table opened. So one more level. We are not really doing anything other than opening a table, expcept stating intent to push it later. The vector knows the type of the type to open. This is a Status table.

[4] `my_ns_info_status_start(&builder) - Lvl = 5 - Type = 5`

Now we have opened a new vector in the nested status table. So level is bumped once more and the type is a vector as expected.

[5] `my_ns_info_status_push_start(&builder) - Lvl = 6 - Type = 3`

And we open yet another table to be pushed onto the info_status vector. This table as type

[6] `attr_infos`. The level is bumped as expected and we have a table type.

`my_ns_status_value_add(&builder, 50) - Lvl = 6 - Type = 3`

Adding to the table, level remains the same (stack grows a bit).

[7] `my_ns_status_attr_infos_start(&builder) - Lvl = 7 - Type = 5`

This is getting weird ... we are now starting an attr_infos vector, but we already did that earlier in [6]. That `attr_infos` table is open and does not have any vector type. The builder is not strongly typed and does not identify this. You are essentially adding an invalid field to the parent attr_infos table.

[8] my_ns_status_attr_infos_push_start(&builder) - Lvl = 8 - Type = 3

And we add another attr_infos table element - but from a false start.

[8] `my_ns_attr_infos_value_add(&builder, flatbuffers_string_create_str(&builder, "TEST VALUE")) - Lvl = 8 - Type = 3`

Value is a string field, so you can do this (except the false start). Yould also do it simpler using `my_ns_attr_infos_value_add_str` (I think), so you could avoid the extra create_str call. It amounts to the same thing internally.

[9] `my_ns_status_attr_infos_push_end(&builder) - Lvl = 7 - Type = 5`

We end the inner attr_infos table, down a level to the offset vector start at [7].

[10] `my_ns_status_attr_infos_end(&builder) - Lvl = 6 - Type = 3`
We end the vector and add it the parent table. Unfortunately this parent table is an `attr_infos` table that will not accept this type, but the builder is not able to catch this mistake.
my_ns_info_status_push_end(&builder) - Lvl = 5 - Type = 5
my_ns_info_status_end(&builder) - Lvl = 4 - Type = 3
my_ns_infovec_info_push_end(&builder) - Lvl = 3 - Type = 5
my_ns_infovec_info_end(&builder) - Lvl = 2 - Type = 3
my_ns_info_end_as_root(&builder) - Lvl = 0 - Type = 0

**Comment by mikkelfj** [comment] 2017-05-12 11:01
I hit the post button a bit early, so the above has been edited.
In summary, the buffer is built incorrectly, but the builder does not have sufficient type info to fail.

We could have used the `type_hash` to store extra type information and catch this during debug. But we don't.

**Comment by epouponstormshield** [comment] 2017-05-12 11:09
Thanks for your explanation!
To sum up the problem: is it related to flatcc or is it related to an incorrect use of the API?

**Comment by mikkelfj** [comment] 2017-05-12 11:10
It's too early - I was confusing my self - not sure if you saw that I just deleted a large dissection. The create_str looks weird, but haven't looked.

**Comment by mikkelfj** [comment] 2017-05-12 11:12
This looks weird and could be a bug - which could explain different behavior between 32-bit and 64-bit. The type should not be -1 - could be an error code of sorts.

my_ns_attr_infos_value_add(&builder, flatbuffers_string_create_str(&builder, "TEST VALUE")) - Lvl = 8 - Type = 65535

**Comment by mikkelfj** [comment] 2017-05-12 11:23
I tried to build on MacOS 64-bit system with clang -m32 - and I did not get any assertions. I suspect it might have to do with reallocation of the stack triggering some bug.

**Comment by mikkelfj** [comment] 2017-05-12 11:34
I'll get back - need to debug this carefully.

**Comment by mikkelfj** [comment] 2017-05-12 12:58
OK, I have yet not found the root cause, but I think I know why 32-bit is different:

```$ cc -Wall -std=c99 test.c -o test -Iflatcc-0.4.1//include/ -DFLATCC_REFLECTION=0 -DFLATCC_PORTABLE flatcc-0.4.1/lib/libflatccrt.a```

We have already seen the type=65535 and this should trigger an assertion. So the assumption is that the 32-bit build is using the debug library `libflatccrt_d.a` and the 64-bit build is using the non-debug library `libflatccrt.a`. If you do not see type=65535 in 64-bit build, please let me know.

**Comment by mikkelfj** [comment] 2017-05-12 13:16
Still no final solution, but I strongly suspect there is a problem in detecting when and how much memory to allocate for additional frames. The default allocation makes space for 8 frames which is exactly where we are, and depending on how you debug, clear_buffer can crash when it attempts to deallocate the frame allocator (buffer index 4) suggestion earlier corruption in the frame. This would also explain why the frame type suddenly goes bad. The string is likely just a random trigger for a corrupt memory condition.

https://github.com/dvidelabs/flatcc/blob/master/src/runtime/builder.c#L530-L545

```
static int enter_frame(flatcc_builder_t *B, uint16_t align)
{
    if (++B->level > B->limit_level) {
        if (B->max_level > 0 && B->level > B->max_level) {
            return -1;
        }
        if (!(B->frame = reserve_buffer(B, flatcc_builder_alloc_fs, B->level * frame_size, frame_size, 0))) {
            return -1;
        }
        B->limit_level = (int)(B->buffers[flatcc_builder_alloc_fs].iov_len / frame_size);
        if (B->max_level > 0 && B->max_level < B->limit_level) {
            B->limit_level = B->max_level;
        }
    } else {
        ++B->frame;
    }
    frame(ds_offset) = B->ds_offset;
    frame(align) = B->align;
    B->align = align;
    /* Note: do not assume padding before first has been allocated! */
    frame(ds_first) = B->ds_first;
    frame(type_limit) = data_limit;
    B->ds_first = alignup(B->ds_first + B->ds_offset, 8);
    B->ds_offset = 0;
    return 0;
}
```

**Comment by mikkelfj** [comment] 2017-05-12 13:54
@epouponstormshield fixed, I hope, please confirm! - change has been committed to master.

```if (!(B->frame = reserve_buffer(B, flatcc_builder_alloc_fs, B->level * frame_size, frame_size, 0))) ```
     
The argument `B->level * frame_size` to reserve is the amount of memory in use. The returned pointer is the next free position in the buffer, following a potential reallocation. The amount of memory is correctly allocated, but because B->level was incremented just before, the initial allocation sets the first frame at index 1 instead of index 0. This means that frame 8 goes off the end because index 0 is wasted. This is actually happening already during initialisation. We don't get the to the point of reallocating again, we crash or corrupt just before.

The following should fix the issue:

```if (!(B->frame = reserve_buffer(B, flatcc_builder_alloc_fs, (B->level * frame_size - 1), frame_size, 0))) ```

and you can also patch 0.4.1 instead if you prefer not to run on master, or more hacky, you could bump the default allocator to a larger value than 8 times frame_size to postpone the problem.

**Comment by epouponstormshield** [comment] 2017-05-12 13:58
Are you sure it is not something like (B->level - 1) * frame_size?

**Comment by mikkelfj** [comment] 2017-05-12 14:05
Yes, that was a type in comment, I already edited it. Should be correct in source.

**Comment by mikkelfj** [comment] 2017-05-12 14:25
I will release 0.4.2 if and when the fix is confirmed to resolve the issue.

**Comment by epouponstormshield** [comment] 2017-05-12 14:39
Sure, I am trying your fix in a more complete environment in order to confirm.
I will tell you as soon as it is good.

**Comment by epouponstormshield** [comment] 2017-05-12 15:04
I confirm the problem is now fixed :)
Thanks for your support on this issue!

**Comment by mikkelfj** [comment] 2017-05-12 15:08
And thanks for a great report. This is a very important bug to get fixed.

**Closed by mikkelfj** 2017-05-12 15:08 UTC
Labels: bug

**Comment by mikkelfj** [comment] 2017-05-12 15:20
0.4.2 has been released.

**Comment by epouponstormshield** [comment] 2017-05-15 07:34
I think it would make sense to extend the existing tests to cover such a use case.
Regards,

**Comment by mikkelfj** [comment] 2017-05-15 07:38
I was thinking about it - and yes it does makes sense up to tiggering the first reallocation. If you feel like it, feel free to contribute. Issue #4 could also such a test case - here the problem was not triggering allocation at all.

**Comment by mikkelfj** [comment] 2017-05-15 07:52
Because such a test would likely need a separate schema, the load_test project could be used as a template rather than extending the monste_test test cases.

https://github.com/dvidelabs/flatcc/tree/master/test/load_test

Note the custom build targets in https://github.com/dvidelabs/flatcc/blob/master/test/load_test/CMakeLists.txt
apperently only works when using Make and not Ninja as build target due to some CMake bug.

**Comment by mikkelfj** [comment] 2017-05-15 07:58
A test is tricky, though, because the default allocator uses an arbitrary limit of 8 frames that might easily be changed, voiding the test case, so at least a source comment is needed, or the use of a custom allocator with know limits.

`int flatcc_builder_default_alloc(void *alloc_context, iovec_t *b, size_t request, int zero_fill, int hint)`
https://github.com/dvidelabs/flatcc/blob/master/src/runtime/builder.c#L107
