### ISSUE TITLE
Problems with compile option -Werror=undef

### ISSUE THREAD

**Issue by kristianQQQ** [dvidelabs/flatcc#111] opened 2019-03-22 07:54 UTC
I have created a schema and generated a header file. Trying to include this header in my project causes problems because the environment I work in forces -Werror=undef, and the flatcc headers in some places rely on undefined macros being zero.

`gcc test.c -Werror=undef -I flatcc\include`

```
flatcc/include/flatcc/portable/pdiagnostic.h:32:5: error: "PDIAGNOSTIC_AWARE_CLANG" is not defined [-Werror=undef]
 #if PDIAGNOSTIC_AWARE_CLANG
     ^
flatcc/include/flatcc/portable/pdiagnostic.h:41:5: error: "PDIAGNOSTIC_AWARE_MSVC" is not defined [-Werror=undef]
 #if PDIAGNOSTIC_AWARE_MSVC
     ^
flatcc/include/flatcc/portable/pdiagnostic.h:43:7: error: "PDIAGNOSTIC_AWARE_CLANG" is not defined [-Werror=undef]
 #elif PDIAGNOSTIC_AWARE_CLANG
       ^
flatcc/include/flatcc/portable/pdiagnostic.h:52:5: error: "PDIAGNOSTIC_AWARE_CLANG" is not defined [-Werror=undef]
 #if PDIAGNOSTIC_AWARE_CLANG

flatcc/include/flatcc/portable/paligned_alloc.h:66:32: error: "_XOPEN_SOURCE" is not defined [-Werror=undef]
 #if (defined _GNU_SOURCE) || ((_XOPEN_SOURCE + 0) >= 600) || (_POSIX_C_SOURCE + 0) >= 200112L
                                ^
flatcc/include/flatcc/portable/paligned_alloc.h:66:63: error: "_POSIX_C_SOURCE" is not defined [-Werror=undef]
 #if (defined _GNU_SOURCE) || ((_XOPEN_SOURCE + 0) >= 600) || (_POSIX_C_SOURCE + 0) >= 200112L
                                                               ^
flatcc/include/flatcc/portable/paligned_alloc.h:68:8: error: "__clang__" is not defined [-Werror=undef]
 #elif (__clang__)

flatcc/include/flatcc/portable/pdiagnostic_pop.h:4:5: error: "PDIAGNOSTIC_PUSHED_MSVC" is not defined [-Werror=undef]
 #if PDIAGNOSTIC_PUSHED_MSVC
     ^
flatcc/include/flatcc/portable/pdiagnostic_pop.h:7:7: error: "PDIAGNOSTIC_PUSHED_CLANG" is not defined [-Werror=undef]
 #elif PDIAGNOSTIC_PUSHED_CLANG

flatcc/include/flatcc/portable/pinline.h:8:7: error: "_MSC_VER" is not defined [-Werror=undef]
 #elif _MSC_VER >= 1500 /* MSVC 9 or newer */
```
Other places in the headers such tests of possibly undefined macros are guarded with defined(), e.g.
`#if defined (__cplusplus) && __cplusplus < 201103L`

I suggest this pattern be used everywhere to prevent the problems above.

**Comment by mikkelfj** [comment] 2019-03-22 08:25
I have been wondering about this myself - when and why it is necessary to check for defined.
Is it a standards violation or just an extra pedantic check?

Fixing this can be a lot of work, with a high risk of doing something wrong because many flags will not be visible on one any given platform.

If you can provide a tested PR that solves the problem for your use case I'd be willing to consider.

Atlernatively, you might be able to override -Werror in pdiagnostic push/pop headers. I could add this.

**Comment by mikkelfj** [comment] 2019-03-22 08:30
Also, I'm not even sure the following is strictly valid:

```#if defined (__cplusplus) && __cplusplus < 201103L```

because you might not be able check for defined and value in the same preprocessor line on some systems, but I don't recall the details.

**Comment by mikkelfj** [comment] 2019-03-22 08:47
The issue is at least with `#elif`: https://github.com/espressif/esp-idf/issues/1585#issuecomment-364066504

The above relates to another flatcc issue: https://github.com/dvidelabs/flatcc/issues/77

See also similar problem here: https://github.com/espressif/esp-idf/issues/991

**Comment by kristianQQQ** [comment] 2019-03-22 09:03
Thanks. The simplest solution for me seems to be overriding the error option. 
```
#pragma GCC diagnostic ignored "-Wundef"
// Including generated header here
#pragma GCC diagnostic error "-Wundef"
```

I can live with doing it this way.

**Comment by mikkelfj** [comment] 2019-03-22 09:20
Do you want to do this in your own code, or should we consider updating the pdiagnostic logic in flatcc?

**Comment by kristianQQQ** [comment] 2019-03-22 09:42
I'm fine with doing it in my own code. But definitely consider fixing it on the flatcc level if you think it will be helpful to others.

**Comment by mikkelfj** [comment] 2019-03-22 09:45
Closing - if others have an issue, we can reconsider, as you say.

**Closed by mikkelfj** 2019-03-22 09:45 UTC
Labels: wontfix

**Comment by the-code-cult** [comment] 2021-08-13 11:23
I am trying to build googletest for bare metal for cross platform projects, (windows  machine, with QNX compiler suite.). Link it later during the actual usage.

There are so many warnings which turned into error because of the compiler config I have -wundef and -werror=undef. 
**_How can I fix these errors through a central CMakeList.txt_**

When  I have no -wundef and -werror -- libraries are generated correctly and verified for the project without any issues. I do not know what were its default values, Now if i define them to default value 0, it is leading to lot of other issues in the compilation.

error: "GTEST_CAN_STREAM_RESULTS_" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_DONT_DEFINE_ASSERT_EQ" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_DONT_DEFINE_ASSERT_GE" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_DONT_DEFINE_ASSERT_GT" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_DONT_DEFINE_ASSERT_LE" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_DONT_DEFINE_ASSERT_LT" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_DONT_DEFINE_ASSERT_NE" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_DONT_DEFINE_FAIL" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_DONT_DEFINE_SUCCEED" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_DONT_DEFINE_TEST" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_ENV_HAS_TR1_TUPLE_" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_FOR_GOOGLE_" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_HAS_ABSL" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_HAS_DOWNCAST_" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_HAS_MUTEX_AND_THREAD_LOCAL_" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_HAS_NOTIFICATION_" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_AIX" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_CYGWIN" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_FUCHSIA" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_HPUX" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_IOS" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_LINUX" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_LINUX_ANDROID" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_MAC" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_NACL" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_OPENBSD" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_SOLARIS" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_SYMBIAN" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_WINDOWS" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_WINDOWS_BOSCH" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_WINDOWS_DESKTOP" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_WINDOWS_MINGW" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_WINDOWS_MOBILE" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_WINDOWS_PHONE" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_WINDOWS_RT" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_OS_ZOS" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_USES_PCRE" is not defined, evaluates to 0 [-Werror=undef]
error: "GTEST_USES_SIMPLE_RE" is not defined, evaluates to 0 [-Werror=undef]
error: "_MSC_VER" is not defined, evaluates to 0 [-Werror=undef]

**Comment by mikkelfj** [comment] 2021-08-13 11:31
@the-code-cult I wouldn't be too worried.
flatcc compiles with aggressive warnings because it is easier to disable warnings that it is use th source in a project with strict warnings with the code falling over.
You are free to relax the warning level in your own build as you please. I suppose you shouldn't start defining flags in GTEST if they are not expected to be defined, but I am not familiar with GTEST.
