### ISSUE TITLE
Tutorial: Weapon_ref_t vs flatbuffers_string_ref_t

### ISSUE THREAD

**Issue by clju** [dvidelabs/flatcc#116] opened 2019-04-22 16:45 UTC
Looking at the flatcc tutorial, I found something strange:

In https://github.com/dvidelabs/flatcc/blob/master/samples/monster/monster.c#L32

Should:
`ns(Weapon_ref_t) weapon_one_name = flatbuffers_string_create_str(B, "Sword");`

not be instead:
`flatbuffers_string_ref_t weapon_one_name = flatbuffers_string_create_str(B, "Sword");
`

I guess it works because it all boils down to a "ref" type (?)
If yes, let me know if I should submit a commit or something. Thanks!

**Comment by mikkelfj** [comment] 2019-04-22 17:26
Yes please do.
Note that the problem is also found here:
https://google.github.io/flatbuffers/flatbuffers_guide_tutorial.html (choose C as language)

**Comment by mikkelfj** [comment] 2019-04-22 17:28
> I guess it works because it all boils down to a "ref" type (?)

That is correct. Good observation.

**Comment by clju** [comment] 2019-04-24 14:48
Uploaded #117.

Not sure where to fix the tutorial though. Is it also on this git repo?

Thanks!

**Comment by mikkelfj** [comment] 2019-04-24 14:59
Great!

> Not sure where to fix the tutorial though. Is it also on this git repo?

No, it is in the main Google flatbuffers repo where the tutorial is the same across multiple languages, but different code snippets.

The flatcc monster sample here follows that tutorial, but adds a few more details.

**Comment by mikkelfj** [comment] 2019-04-24 17:50
Fixed in https://github.com/google/flatbuffers/pull/5305 and #117

Thanks!

**Closed by mikkelfj** 2019-04-24 17:50 UTC
Labels: bug
