### ISSUE TITLE
Flactcc falls into an infinite loop when generate a table with id attributes

### ISSUE THREAD

**Issue by charleszhangjie** [dvidelabs/flatcc#112] opened 2019-03-29 04:09 UTC
Thank-you for creating a great library! I encounter a problem when using flatcc compiler to generate code in C language.

# Steps to reproduce the problem

1. I write a schema to define a table with id attribute on table field. Here is the example.
I did not place the fields in sequence order and put the max id at last.
    ```
    namespace example;

    table x {
      b:int (id:2);
      a:int (id:0);
      c:int (id:1);
      d:int (id:3);
    }
    ``` 

2. Run the flatcc (or flatcc_d) compiler to generate code
    
   ```
   flatcc_d -w example.fbs
   ```
   
3. Nothing output and the program falls into an infinite loop

# The version of the flatcc and the operating system
The version of flatcc (on unix system) I used is
```
    flatcc FlatBuffers schema compiler for C by dvide.com
    version: 0.6.0-pre
```

# Debug flatcc_d with GDB tools
I debug running flatcc_d and trace to the following code (`flatcc-master/src/compiler/semantics.c:1324`): 
```
    /*
     * Reorder by id so table constructor arguments in code
     * generators always use same ordering across versions.
     */
    for (sym = ct->members; sym; sym = sym->link) {
        member = (fb_member_t *)sym;
        field_index[member->id] = sym;
    }
    j = 0;
    if (field_index[0] == 0) {
        j = 1; /* Adjust for union type. */
    }
    ct->members = field_index[j];
    for (i = j + 1; i < max_id; ++i) {
        if (field_index[i] == 0) ++i; /* Adjust for union type. */
        field_index[j]->link = field_index[i];
        j = i;
    }

```
I think the second loop condition `i < max_id` SHOULD BE `i <= max_id`, because the field with max id must be linked with the previous one,
 
if the '=' missed, in my test case, the second last member link to the wrong object resulting in in a loop occurs in `ct->members` unexpectedly:

In my case, the original member link is `2 -> 0 -> 1 -> 3`, and reordered members should be `0 -> 1 -> 2 -> 3`.
But as the code above running, it reordered members as `0 -> 1 -> 2 -> 0`, because `field_index[2]->link` was not modified to `field_index[3]` due to the loop reached the exit condition.

I try to modify  `i < max_id` to `i <= max_id` and rebuild the tool, the problem no longer reappears.

Is it an issue in `flatcc-master/src/compiler/semantics.c` and did I fix it correctly?

**Comment by mikkelfj** [comment] 2019-03-29 05:44
Hi Charles,

thanks for reporting this and debugging this tricky problem.
Yes, your fix is correct. Do you wan't to submit a PR, or should I can just commit the change?

Strictly speaking the is a previous loop reporting missing id errors where it is also `<` instead of `<=` but since it looks for gaps and `max_id` is not a gap, it is probably fine, and perhaps intentional - but unfortunately leading to the later mistake.

**Comment by charleszhangjie** [comment] 2019-03-29 06:43
Hi mikkelfj,
I submit a PR to fix it. You can help edit the information because it is my first time to submit a pull request on GitHub.

**Comment by mikkelfj** [comment] 2019-03-29 06:50
That is fine thanks!

**Comment by charleszhangjie** [comment] 2019-03-29 09:10
Sorry to tell you that it still has some mistake.
when I write a schema to define a table which the first field has the max_id, flatcc falls into endless loop again.
I think I should add `field_index[max_id]->link = NULL;` after the loop ):  because the last member must link to null.
the correct code seems like:
```
        /*
         * Reorder by id so table constructor arguments in code
         * generators always use same ordering across versions.
         */
        for (sym = ct->members; sym; sym = sym->link) {
            member = (fb_member_t *)sym;
            field_index[member->id] = sym;
        }
        j = 0;
        if (field_index[0] == 0) {
            j = 1; /* Adjust for union type. */
        }
        ct->members = field_index[j];
        for (i = j + 1; i <= max_id; ++i) {
            if (field_index[i] == 0) ++i; /* Adjust for union type. */
            field_index[j]->link = field_index[i];
            j = i;
        }
        field_index[max_id]->link = NULL;
```

**Comment by mikkelfj** [comment] 2019-03-29 10:20
That would be necessary if fields are not zero initialized, or if the link field is somehow assigned at an earlier stage. This needs to be investigated, otherwise it could mask other problems.

I'm not sure why the CI build fails, but something goes bad.

On code style: I use 0 instead of NULL (non-standard, but I never saw the point).

**Comment by mikkelfj** [comment] 2019-03-29 10:25
Note: on pull request - it would be better to base the new pull request on the latest committed version where `<=` is already fixed - but it doesn't really matter since I squash merge.

**Comment by mikkelfj** [comment] 2019-03-29 10:34
The sym->link is the default ordering when parsed, and reorder shuffles those links. Therefore you are correct that there is a missing null terminator.

When I apply the change locally on MacOS, all tests pass. We need to figure out why the CI builds fail.

**Comment by mikkelfj** [comment] 2019-03-29 10:36
Oops, no, things break locally too. If you run scripts/test.sh you should see it too.

**Comment by mikkelfj** [comment] 2019-03-29 11:04
I think the problem is `need_id`. It is only set with user assigned id attributes. If it is not set, then max_id is also not set. Hence testing for count > 0 is not enough.

However, there are other problems: `need_id` is only set when `count = 0`, but it should probably be set regardless of count. I think I made this incorrect change no so long ago.

I'll look into this and probably commit some changes and ask you to verify your specific case.

**Comment by mikkelfj** [comment] 2019-03-29 11:12
Please check 5fb46669e9fab67be1d54d040813a1b2090ea7c2

**Comment by mikkelfj** [comment] 2019-03-29 11:13
BTW: `need_id` is set correctly - there are later checks in place that deals with this.

**Comment by charleszhangjie** [comment] 2019-03-30 00:29
I checked 5fb4666, and all my specific cases passed.

**Comment by mikkelfj** [comment] 2019-03-30 06:59
great, thanks!

**Closed by mikkelfj** 2019-03-30 06:59 UTC
Labels: bug
