### ISSUE TITLE
Segfault when using _pick in certain circumstances

### ISSUE THREAD

**Issue by AndrewJDR** [dvidelabs/flatcc#102] opened 2018-12-31 09:00 UTC
I seem to have stumbled upon a segfault when using _pick() under particular circumstances. I've submitted a PR #101 with a repro. I'll paste the PR description here as well:

> To repro, compile and run monster_test_d.
> 
> See backtrace.txt and search for "XXX" inside of the following files
> for important notes regarding the issue:
> test/monster_test/monster_test.c
> test/monster_test/pick_test.fbs
>
> Perhaps this is an incorrect library usage somewhere, but it certainly seems odd.
> 
> I've commented out all other tests for now, mainly to simplify my workflow while working on this issue, but also because the rest of the monster tests weren't playing nice with this one when I tried to compile everything together.

Backtrace:
```
Program received signal SIGSEGV, Segmentation fault.

Stack
[0] from 0x00007ffff7a91f78
[1] from 0x00007ffff7a93ae0 in malloc+-3531168
[2] from 0x00007ffff7a83142 in vasprintf+34
[3] from 0x00007ffff7a65597 in asprintf+135
[4] from 0x00007ffff7a40b52
[5] from 0x00007ffff7a40ca2 in __assert_fail+66
[6] from 0x000000000042c9b3 in _create_offset_vector_direct+852 at /home/dev/src/flatcc/src/runtime/builder.c:1468
[7] from 0x000000000042ca1d in flatcc_builder_create_offset_vector_direct+45 at /home/dev/src/flatcc/src/runtime/builder.c:1478
[8] from 0x000000000042ca7a in flatcc_builder_end_offset_vector+91 at /home/dev/src/flatcc/src/runtime/builder.c:1486
[9] from 0x000000000041b236 in PickTest_MA_vec_clone+244 at /home/dev/src/flatcc/build/lindebug/test/monster_test/generated/pick_test_builder.h:54
[10] from 0x000000000041fc40 in PickTest_State_ma_clone+35 at /home/dev/src/flatcc/build/lindebug/test/monster_test/generated/pick_test_builder.h:492
[11] from 0x000000000041fc8c in PickTest_State_ma_pick+58 at /home/dev/src/flatcc/build/lindebug/test/monster_test/generated/pick_test_builder.h:492
[12] from 0x00000000004247b1 in test_pick_copy+4454 at /home/dev/src/flatcc/test/monster_test/monster_test.c:1203
[13] from 0x0000000000428a2e in main+78 at /home/dev/src/flatcc/test/monster_test/monster_test.c:2856
```

**Comment by mikkelfj** [comment] 2018-12-31 11:55
Thanks, I'll have a look in the next few days.

**Comment by mikkelfj** [comment] 2019-01-02 10:36
I ran "lldb monser_test_d"

It failed on an assertion about null elements in vector. This does not explain why that happens, but perhaps it is a hint that can you investigate further while I also look into it. (I  had to use "up" a few times in lldb to get past some assembly frames).

```
frame #4: 0x0000000100034852 monster_test_d`_create_offset_vector_direct(B=0x00007ffeefbff5c0, vec=0x0000000100303380, │
count=26, types=0x0000000000000000) at builder.c:1468                                                                  │
   1465             if (types) {                                                                                       │
   1466                 check(types[i] == 0, "union vector cannot have null element without type NONE");               │
   1467             } else {                                                                                           │
-> 1468                 check(0, "offset vector cannot have null element");                                            │
   1469             }                                                                                                  │
   1470         }                                                                                                      │
   1471     }
```

**Comment by mikkelfj** [comment] 2019-01-02 11:07
This is the code in flatbuffers_common_builder.h which executes during the assertion, in the call to `flatbuffers_end_offset_vector`, noting that the vector has 26 elements when calling `flatcc_builder_create_offset_vector_direct` according to the debugger:

```
static inline N ## _vec_ref_t N ## _vec_clone(NS ## builder_t *B, N ##_vec_t vec)\
290 { int _ret; N ## _ref_t *_p; size_t _i, _len; __flatbuffers_memoize_begin(B, vec);\
291  _len = N ## _vec_len(vec); if (flatcc_builder_start_offset_vector(B)) return 0;\
292   _p = flatcc_builder_extend_offset_vector(B, _len); if (!_p) return 0;\
293   for (_i = 0; _i < _len; ++_i) { if (!(_p[_i] = N ## _clone(B, N ## _vec_at(vec, _i)))) return 0; }\
294   __flatbuffers_memoize_end(B, vec, flatcc_builder_end_offset_vector(B)); }\
```

**Comment by mikkelfj** [comment] 2019-01-02 11:20
I have a possible idea of what might be going wrong: I still don't fully understand the test case and schema, but it seems that a vector containing tables is being cloned. The outer vector reserves space for its length in the call to `flatcc_builder_extend_offset_vector`, then it proceeds to call clone on each individual element. All construction happens on a single data stack (ds) and `p_[i]` points into that stack. When a child element is constructed, a new internal stack frame is constructed and eventually popped when it is moved to the final buffer memory. `p_[i]` then stores the buffer offset` in the vector in the parent frame, then the process repeats for all `i`. The parent vector will never overflow because the size is known in advance. However, each child element using additional temporary stack space might trigger a stack reallocation. This invalidates the `p_` pointer value which should have been updated based on the ds offset rather than an absolute pointer value. This is done with a refresh call.

This would explain your memory assertion, but not my null offset assertion. However, my assertion could be an artefact from accidentally using valid memory without incorrect content.

**Comment by mikkelfj** [comment] 2019-01-02 13:46
The way to recover the `_p` pointer value is to reassign it with `flatbuffers_offset_vector_edit(B)` after it has been invalidated. An alterantive approach is to not preallocate the vector and push each element instead since the push operation does not use a stored pointer. I used push to fix vec_clone for offset vectors and for unions.

https://github.com/dvidelabs/flatcc/commit/f4126fb614cd4c3c914b2f9a12fbc69fdf5cb6e8

It seems to work in your test case, please have a look.

You are welcome to add a test case if you can integrate it more cleanly into the current monster test. Note that unions haven't really been tested, but they are cloned by cloning a type vector first, then an offset vector, so the problem is largely the same.

**Comment by AndrewJDR** [comment] 2019-01-03 00:33
Yep, can confirm that f4126fb also fixes it in the original application where I was experiencing the segfault, thank you!

When I was building this repro, I was to get it integrated into the monster schema but just couldn't get it to crash, so I ended up just porting over and somewhat simplifying the original implementation code. Even then, the crash was very particular, to the point where if I commented out even a single field _add call anywhere in the code, or removed some fields in the schema from a particular table, the crash would no longer happen.... which did make it smell like a reallocation thing.

I could probably significantly clean up this code so that it's not _pick()ing from a bunch of separate  builders (which is an artifact of the original implementation that is probably not necessary for the segfault to occur) and pull it out into a test separate from the monster one, but I think simplifying it beyond that is probably more trouble than it's worth. If there's still interest in a test like that, let me know.

**Comment by mikkelfj** [comment] 2019-01-03 09:54
OK thanks for explaining and confirming. There are lots of cases one could imagine creating for reallocation, also in other areas, but in the end this is just one of those core areas that has to be written correctly once and for all, and which are quite tricky to test fully, so I wouldn't bother if the test is not easy. I'm more concerned about cloning union vectors in any case.

**Closed by mikkelfj** 2019-01-03 09:54 UTC
