### ISSUE TITLE
 table verify always fails

### ISSUE THREAD

**Issue by vk-coder** [dvidelabs/flatcc#127] opened 2019-09-18 19:17 UTC
Using latest GIT pull

# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 

# uname -a
Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

IDL definition

```
table EthEndpointState
{
...
}

table WifiEndpointState
{
...
}

union EndpointConnectionState
{
    EthEndpointState,
    WifiEndpointState
}

table Message
{
    connection_state: EndpointConnectionState;
}

root_type Message;

```

I am trying to create a flatbuffer from table Message which I will add as String field in some other flatbuffer IDL.
I have added code to add union data as well but verify was failing so I removed all the union code and just kept following code still verify is failing.

```
flatcc_builder_t builder1;
flatcc_builder_init(&builder1);
Message_start(&builder1);
Message_end(&builder1);
size_t size;
void *buf = flatcc_builder_get_direct_buffer(&builder1, &size);
int ret;
if ((ret = ns(Message_verify_as_root)(buf, size))) {
    printf("could not verify Message table, got %s\n", flatcc_verify_error_string(ret));
}

could not verify Message table, got table header out of range or unaligned
```

**Comment by vk-coder** [comment] 2019-09-18 20:00
I think i understood where it's failing. first of all I should use `Message_start_as_root` and `Message_end_as_root`. but even after that it was failing. then I disabled / enabled field by field and realized that EthEndpointState has it's first field defined as `uint64 `and this is where the problem is. i don't know why but if i change it to just `int`, everything works fine. the moment I define the field as `uint64 `verify fails.

**Comment by mikkelfj** [comment] 2019-09-18 21:27
Can you check check if the returned buffer is aligned to 64 bit? Just print the pointer as hex?
If only the lower two bits are zero, try copy to an aligned address and repeat verification.

Get direct buffer ought to return an aligned address but it could be the problem.

**Comment by mikkelfj** [comment] 2019-09-18 21:44
I think I know what the problem is - but the above still stands.

The direct buffer is placed in page of ca. 2K size. The buffer is by default allocated using malloc. Malloc generally aligns to 8 bytes (64-bit). For technical reasons the buffer starts in the middle of buffer and grows downwards. Alignment is relative to that starting point (or rather endpoint). So even if the buffer is technically padded correctly to 8-bytes alignment that start will not be if the end isn't.

`E->front_cursor = E->front->page + FLATCC_EMITTER_PAGE_SIZE / 2;`

The division halves the alignment. Sometimes malloc is aligned to more than 64-bits and then there is no problem, but sometimes it isn't.

You can always get around this problem by copying out the buffer as is done in the monster example.

But, it is actually worse because it is possible to write 64-bit values on a 32-bit address boundary which can cause an access violation on some platforms. I have never heard about it, but still. This part needs to get fixed. Once fixed, get_direct_buffer should guarantee 64-bit alignment but no more than that. Some buffers can require a higher alignment but it would not cause access violations while creating the buffer.

**Comment by mikkelfj** [comment] 2019-09-18 21:48
No, that can't be true (it's late here). `E->front->page + FLATCC_EMITTER_PAGE_SIZE / 2;` should still be an aligned address because it is adding a higher power of two to the start address, which should be at least 64-bit aligned. So, at least that part should be correct.

**Comment by vk-coder** [comment] 2019-09-19 13:42
here is the hexdump where the IDL has uint64

```
the message sent from one process
outgoing Message:
00000000  04 00 00 00 cc ff ff ff  01 00 00 00 04 00 00 00  |................|
00000010  e4 ff ff ff 02 00 00 00  00 00 00 00 01 00 00 00  |................|
00000020  01 00 00 00 c9 50 db 41  00 00 00 00 0c 00 18 00  |.....P.A........|
00000030  04 00 0c 00 10 00 14 00  08 00 0c 00 04 00 08 00  |................|

message is received by other process
incoming Message:
00000000  04 00 00 00 cc ff ff ff  01 00 00 00 04 00 00 00  |................|
00000010  e4 ff ff ff 02 00 00 00  00 00 00 00 01 00 00 00  |................|
00000020  01 00 00 00 c9 50 db 41  00 00 00 00 0c 00 18 00  |.....P.A........|
00000030  04 00 0c 00 10 00 14 00  08 00 0c 00 04 00 08 00  |................|
could not verify Message table, got table field not aligned

```

here is the working hexdump when I change uint64 to int

```
the message sent from one process
outgoing Message:
00000000  04 00 00 00 d4 ff ff ff  01 00 00 00 04 00 00 00  |................|
00000010  ec ff ff ff 02 00 00 00  01 00 00 00 01 00 00 00  |................|
00000020  64 e0 81 71 0c 00 14 00  04 00 08 00 0c 00 10 00  |d..q............|
00000030  08 00 0c 00 04 00 08 00                           |........|

message is received by other process
incoming Message:
00000000  04 00 00 00 d4 ff ff ff  01 00 00 00 04 00 00 00  |................|
00000010  ec ff ff ff 02 00 00 00  01 00 00 00 01 00 00 00  |................|
00000020  64 e0 81 71 0c 00 14 00  04 00 08 00 0c 00 10 00  |d..q............|
00000030  08 00 0c 00 04 00 08 00                           |........|

```

**Comment by mikkelfj** [comment] 2019-09-19 13:51
Thanks for providing more details.

If you look at the second hex table, second row:
`00000010  e4 ff ff ff 02 00 00 00  00 00 00 00 01 00 00 00`
The 64-bit integer is located at offset 4 in the row: `02 00 00 00  00 00 00 00`
Offset 4 is not a good location for a 64-bit value. This is why the verifier complains.

But now I need the exact schema and example code to see what you are doing because I can see you have two tables in the buffer, and the second table (the above dump) is not properly aligned. I need to know why that happens - either to find a problem in your code, or to have something to debug.

**Comment by vk-coder** [comment] 2019-09-19 14:03
Here are the details.


this is the inner schema

```
table EthEndpointState
{
    endpoint_id: int;  // uint64 fails
    state: int;
    type: int;
}

table WifiEndpointState
{
    endpoint_id: int; // uint64 fails
    state: int;
    type: int;
    pp_id: int;
}

union EndpointConnectionState
{
    EthEndpointState,
    WifiEndpointState
}

table Message
{
    connection_state: EndpointConnectionState;
}

root_type Message;
```



this is the outer schema

```
enum MessageType:int 
{
    MessagingPayload = 0,
    ApplicationPayload = 1
}

table SelfIPCMessage
{
    type:MessageType;
    payload:string;
}

root_type SelfIPCMessage;

```

this is how i am encoding it

```
flatcc_builder_t builder1;
flatcc_builder_init(&builder1);
ns(EthEndpointState_start)(&builder1);
ns(EthEndpointState_endpoint_id_add(&builder1, endpoint->id));
ns(EthEndpointState_state_add)(&builder1, CONNECTION_STATE_CONNECTED);
ns(EthEndpointState_type_add)(&builder1, MESSAGING_ETH_ENDPOINT);
ns(EthEndpointState_pipe_id_add)(&builder1, pipe_id);
EthEndpointState_ref_t eth_ep = ns(EthEndpointState_end)(&builder1);

Message_start_as_root(&builder1);
Message_connection_state_add(&builder1, EndpointConnectionState_as_EthEndpointState(eth_ep));
Message_end_as_root(&builder1);

size_t size;
void *buf = flatcc_builder_get_direct_buffer(&builder1, &size);

flatcc_builder_t builder;
flatcc_builder_init(&builder);
ns(SelfIPCMessage_start_as_root)(&builder);
ns(SelfIPCMessage_type_add)(&builder, ns(MessageType_MessagingPayload));
ns(SelfIPCMessage_payload_create)(&builder, buf, size);
ns(SelfIPCMessage_end_as_root)(&builder);

buf = flatcc_builder_get_direct_buffer(&builder, &size);  // this buf is sent over TCP to other process
```

this is how i am decoding it

'msg' is where the buffer is read from TCP endpoint;

```
int ret = ns(SelfIPCMessage_verify_as_root)(msg, msg_len);
if (ret) {
    printf("could not verify SelfIPCMessage table, got %s\n", flatcc_verify_error_string(ret));
    return 0;
}
ns(SelfIPCMessage_table_t) message = ns(SelfIPCMessage_as_root)(msg);
if (message) {
    int type = ns(SelfIPCMessage_type(message));

    if (ns(MessageType_MessagingPayload) == type) {
        flatbuffers_string_t payload;
        payload = ns(SelfIPCMessage_payload)(message);

        ret = ns(Message_verify_as_root)(payload, flatbuffers_string_len(payload));
        if (ret) {   // this fails when IDL has uint64 for endpoint_id
            printf("could not verify Message table, got %s\n", flatcc_verify_error_string(ret));
            return 0;
        }

        ns(Message_table_t) msg = Message_as_root(payload);

        if (Message_connection_state_is_present(msg)) { // this started crashing hence added above verify condition which started failing
            if (ns(Message_connection_state_type(msg)) == ns(EndpointConnectionState_EthEndpointState)) {

                ns(EthEndpointState_table_t) Eth_ep = (ns(EthEndpointState_table_t))ns(Message_connection_state(msg));

                printf("Eth endpoint connection state, endpoint id : %d, pipe id : %d, state : %s, endpoint-type: %s\n",
                       ns(EthEndpointState_endpoint_id(Eth_ep)),
                       ns(EthEndpointState_pipe_id(Eth_ep)),
                       ns(EthEndpointState_state(Eth_ep)) == STATE_ADD? "added" : "deleted",
                       ns(EthEndpointState_type(Eth_ep)) == MESSAGING_ETH_ENDPOINT? "Eth" : "Wifi");
            }
        }
    } 
    ...
}


```

**Comment by mikkelfj** [comment] 2019-09-19 14:25
Thanks. I'll need some more time, but some immediate comments that do not explain the hexdump we have seen:

1. you should preferably not store buffers as strings. It is better to user [uint8] arrays. There is a nested flatbuffer concept for that, but you can also just use an array. While strings can hold any data, they are generally expected to be UTF-8. If you need a string type at the top level as an alternative message type, you can have a separate field of string type. The space is only used when written to (except a few bytes for a larger vtable).

2. There are many indirections here - it would be better if you could limit this to a single top-level union - but there is nothing wrong with the approach as such - except for the complications listed below:

3. When you receive the buffer over the network, the top-level buffer must be aligned sufficiently. I cannot see if you do this or not, but usually malloc is enough (up to 64-bits). Otherwise verify will fail even on platforms where alignment isn't critical.

4. The inner buffer will be 4-byte aligned because that is the minimum alignment a string can have. There is a 50% chance of this being correct when the buffer needs 64-bit alignment (8-byte alignment). You must copy the buffer elsewhere if you need to verify even if the platform doesn't care when reading. (I have a long standing wish for optionally being able verify a buffer stored in unaligned memory, as long as the buffer is correctly aligned relative to its start). If you do not copy, you risk a crash on some platforms aside from verification issues.

5. If you use nested flatbuffers, and if you use a single flatcc builder to create both buffers using the dedicated nested buffer calls, then the nested buffer will be correctly aligned and you won't have the above mentioned problem. However, this problem may still exist if the buffer is created by another implementation that does not correctly align nested buffers - this has been an issue in the past.

Now, none of this explains why the integer starts at an odd location. I'll need to dig into this.

**Comment by mikkelfj** [comment] 2019-09-19 14:48
This looks wrong wrt. alignment but the alignment would be correct if there were a file identifier, except there isn't in this case (which is valid).

A buffer usually has a 4-byte identifier at byte offset 4 when the schema has a `file_identifier`. The field can also be omitted if you tell the build so, but you don't.

I wonder if the builder thinks that it has an identifier when it actually doesn't, and therefore misaligns. What happens if you add a file_identifier field alog with the 64-bit field?

**Comment by vk-coder** [comment] 2019-09-19 14:55
without changing any flags for the builder, adding file identifier and chaning field to uin64 i get following error for the inner schema.

could not verify Message table, got table field not aligned

**Comment by mikkelfj** [comment] 2019-09-19 15:29
OK, thanks. I can't find any obvious mistakes in your code so I'll try to reproduce.

**Comment by mikkelfj** [comment] 2019-09-19 15:31
Note: if, theoretically, the file identifier fixes the problem, you could still see the verify problem if you don't copy out the inner buffer to an aligned address.

**Comment by mikkelfj** [comment] 2019-09-19 16:54
I have now reproduced the problem. I needed to comment out `//ns(EthEndpointState_pipe_id_add)(&builder1, pipe_id);` because it wasn't in the schema.

You can create a similar test project using:

mkdir tmp
scripts/setup.sh -s tmp/issue127
cd tmp/issue127
Add the following to src/main.c, and add the two schema as `src/inner.fbs` and `src/outer.fbs` respectively. The run `scripts/build.sh && build/issue127_d`.

I get "inner buffer is valid" no matter what I do. I'm not sure when you call verify, but as stated, you receiving code has some alignment issues. Calling verify directly after construction does not cause a verifier fail.

However, the buffer is actually invalid even if the verifier accepts (unless I miss something) - because the address of field is not 8 byte aligned in the hexdump. This suggests the compiler believes uint64 is aligned to less than it should be.

Furthermore, if a add `file_identifier "innr";`  to the inner schema, the alignment is in fact correct. This is also true when I change the other field types to uint8 and reorders the code to write fields in a different order. In all cases it appears the field is correctly aligned.

This leads me to conclude that there is some sort of bug in flatcc that doesn't usually surface, either because file_identifier is being used, or because the verifier has the same issue and end users do not use the code on a platform that crashes on 32-bit alignment even for 64-bit access.

```c
#include "../generated/inner_builder.h"
#include "../generated/inner_verifier.h"
#include "../generated/outer_builder.h"
#include "flatcc/support/hexdump.h"

#define ns(x) x

#define CONNECTION_STATE_CONNECTED 1
#define MESSAGING_ETH_ENDPOINT 2
#define pipe_id 3

struct endpoint {
    uint64_t id;
};

void encode()
{
    int ret;
    struct endpoint endpoint[1] = { { 42 } };
    flatcc_builder_t builder1;
    flatcc_builder_init(&builder1);
    ns(EthEndpointState_start)(&builder1);
    ns(EthEndpointState_endpoint_id_add(&builder1, endpoint->id));
    ns(EthEndpointState_state_add)(&builder1, CONNECTION_STATE_CONNECTED);
    ns(EthEndpointState_type_add)(&builder1, MESSAGING_ETH_ENDPOINT);
    //ns(EthEndpointState_pipe_id_add)(&builder1, pipe_id);
    EthEndpointState_ref_t eth_ep = ns(EthEndpointState_end)(&builder1);

    Message_start_as_root(&builder1);
    Message_connection_state_add(&builder1, EndpointConnectionState_as_EthEndpointState(eth_ep));
    Message_end_as_root(&builder1);


    size_t size;
    void *buf = flatcc_builder_get_direct_buffer(&builder1, &size);
    hexdump("inner buffer", buf, size, stderr);
    if ((ret = ns(Message_verify_as_root(buf, size)))) {
        printf("could not verify Message table, got %s\n", flatcc_verify_error_string(ret));
        exit(1);
    }
    printf("inner buffer is valid");

    flatcc_builder_t builder;
    flatcc_builder_init(&builder);
    ns(SelfIPCMessage_start_as_root)(&builder);
    ns(SelfIPCMessage_type_add)(&builder, ns(MessageType_MessagingPayload));
    ns(SelfIPCMessage_payload_create)(&builder, buf, size);
    ns(SelfIPCMessage_end_as_root)(&builder);

    buf = flatcc_builder_get_direct_buffer(&builder, &size);  // this buf is sent over TCP to other process
}

int main()
{
    encode();
    return 0;
}
```

**Comment by vk-coder** [comment] 2019-09-19 17:01
yes, i was about to comment the same, verify immediate after building the message always succeeds on sender side. Verify always fails with uint64 but not when the type is int on receiver side.

i do not have file identifiers set for any of my schema. Sender and receiver use TCP pipe for communication.

Appreciate your efforts debugging this.

**Comment by jobol** [comment] 2022-01-19 10:45
A colleague encountered a similar issue when using doubles.

In my mind, the alignment can be correct at build but when sent it fails. I quick fix could but to insert 4 null bytes after the initial offset when it is needed. Tracking when it is needed is not so hard:

-  when the buffer is built, alignment is correctly set (i presume)
- before inserting the start offset (4bytes)
   - if the alignment is 4 modulo 8, it is okay
   - if the alignment is 0 modulo 8, it is not okay if doubles or int64 are present

Not sure about format verification if it is before, after and when to take it into account

**Comment by mikkelfj** [comment] 2022-01-19 11:36
It's a complicated debugging scenario when building the table. What makes it align relative to absolute address instead of relative to buffer start? If that is indeed the problem. And is it always the same for all fields or not? Adding a simple heuristic hack could make things worse if assumptions are wrong. The fix is probably trivial once understood.

**Comment by jobol** [comment] 2022-01-19 13:21
My understanding is that the buffer when received start on a 8 bytes compatible alignment. If this is not the case then nothing is possible. So it must be the case: the received buffer is stored starting on a multiple of byte boundary. Then by inserting or not 4 bytes, you can ensure the alignment of int64 or double.
That is true that for fields, the logic of alignment must rely on some reference. When building the buffer by its 2 sides, fixing a reference is less obvious but not difficult. Then using that reference to ensure correct alignment at the end should be possible.
Using absolute address for reference is not in my mind and difficult to use because of possible reallocations/rellocations.

**Comment by mikkelfj** [comment] 2022-01-20 09:55
@jobol  I'm mere stating absolute address because verify apparently passed sender side, not receiver side. But I no longer recall all the details and will need to revisit. It is rather strange and should be fixed. If you have easy to reproduce cases, please save them. If you are up for debugging, be my guest - but we need to understand the root cause.  As to fixing when building: yes it should be easy to fix, once you understand exactly what goes wrong - there are plenty of tools insert padding pre- and post-insertion. However, it gets more complicated when also dealing when nested buffers.

**Comment by mikkelfj** [comment] 2022-01-20 10:00
However, if the receiver side is NOT aligned to 8 bytes which it normally would be with malloc, depending on the system, then the verifier would and should fail on 8 byte data types. Unfortunately it seems to not just be that.

Another issue is that it would be good to have a verifier option that only verifies relative to buffer start and not stored location because that is convenient in data transmission on systems that do not require strict alignment.

**Comment by jobol** [comment] 2022-01-20 12:00
@mikkelfj after reading you I ask me if my scanned buffer is really 8 bytes aligned. The receive buffer probably yes but if have not taken care in the transmission protocol of being 8 bytes aligned for data. I'm going to check on my side.
Nevertheless, the buffers shown above (https://github.com/dvidelabs/flatcc/issues/127#issuecomment-533136512) look bad IMHO.

**Comment by mikkelfj** [comment] 2023-10-25 20:55
I have looked at this again. I have not gotten to the bottom of the issue but noted the following:

get_direct_buffer is not guarenteed to return alignment beyond 4 bytes.
This is why the verifier accepts a buffer that should not be accepted. The internal buffer is always aligned by some standard allocation unit, typically 8 bytes. So as the buffer is always built the same way, we happen to always get a buffer that consistently is aligned to 4 but not 8 bytes. This compensates for the 8 byte field that is not correctly aligned.

To get a properly aligned buffer use:
```
void *buf = flatcc_builder_finalize_aligned_buffer(&builder1, &size);
```
instead of
```
void *buf = flatcc_builder_get_direct_buffer(&builder1, &size);
```

This still does not explain why the 8 byte field is not correctly aligned, but I wanted to make a note of this finding.
Thus the verifier is actually not failing in this case, but something is not being built correctly.

**Comment by mikkelfj** [comment] 2023-10-25 21:14
Thinking some more, I think the problem is actually that get_direct_buffer ought to be aligned to at least malloc, which is typically 8 bytes or more, so it might not be coincidence that it verifies correctly. At least it gives something to investigate.

**Comment by mikkelfj** [comment] 2023-10-26 19:02
I have finally fixed it.
This problem is caused by the example source code creating objects before the buffer is started. _create_as_root calls have an implicit call to start buffer. The documentation says this is actually OK, but only at the top level (not nested buffers). The problem was that the minimum required alignment computed before the buffer was started, would be ignored because start buffer resets such data.

The example in this issue could be rewritten to work, so this is not global alignment issue and limited to this edge case.

I have opted to fix the issue by including alignment computations present between builder init and buffer start, and this seems to fix the issue both with and without finalize_aligned and get_direct buffer: 62dea78ae09bac1b569c6aefdb25defe839bdf88

NOTE: objects cannot be created before a nested buffer because the objects must be stored inside the embedded buffer which will not happen in that case. So the fix is only for top level buffers.

**Closed by mikkelfj** 2023-10-26 19:02 UTC
Labels: bug
