### ISSUE TITLE
increase of "buffer header too small" and "table header out of range or unaligned" messages

### ISSUE THREAD

**Issue by AndrewJDR** [dvidelabs/flatcc#60] opened 2017-10-01 06:29 UTC
Firstly, apologies in advance for the vagueness.

I can fill this in with more detail/debugging/bisecting/etc later if this doesn't ring a bell for you off the bat.

Somewhere in the range of d9a75592e27756e..v0.4.3 I started getting a lot more of these kinds of warnings on my buffers during verify:
buffer header too small
table header out of range or unaligned

Can you think of what might have started this of the top of your head?
I didn't change any build settings between building d9a75592e and v0.4.3.

**Comment by mikkelfj** [comment] 2017-10-01 07:30
Hi Andrew, there was a fix to vector alignment in the verifier at 7c6bda5b which shows up with

git log d9a75592..v0.4.3 --graph
changelog: Fix verifier vector alignment check - affects vectors with element size 8+.

There is also changelog: Allow more costumization of allocation functions

It shouldn't do anything, but since some allocation methods have been moved, it might have gone awry somehow. 3f3ab116 a2de05f 11d43b62 1a780fb these also shows up in the log command from above.

**Comment by mikkelfj** [comment] 2017-10-01 09:44
Were the failing buffers build with the same version as the verifier, or from older persisted data?

**Comment by AndrewJDR** [comment] 2017-10-01 09:48
Actually the buffers are being built by js code, which necessitates using google's flatbuffer library. i.e.
google's flatbuffer lib (with js) for build -> flatcc for verify/parse

**Comment by mikkelfj** [comment] 2017-10-01 09:50
I think I might have found the issue?
```
| diff --git a/src/runtime/verifier.c b/src/runtime/verifier.c                                                         │
| index f8ae074..c918a1b 100644                                                                                        │
| --- a/src/runtime/verifier.c                                                                                         │
| +++ b/src/runtime/verifier.c                                                                                         │
| @@ -142,6 +142,9 @@ static inline int check_aligned_header(uoffset_t end, uoffset_t base, uoffset_t                  │
|      if (uoffset_size <= voffset_size && k + offset_size < k) {                                                      │
|          return 0;                                                                                                   │
|      }                                                                                                               │
| +    /* Alignment refers to element 0 and header must also be aligned. */                                            │
| +    k += uoffset_size;                                                                                              │
| +    align = align < uoffset_size ? uoffset_size : align;                                                            │
|                                                                                                                      │
|      /* Note to self: the builder can also use the mask OR trick to propagate `min_align`. */                        │
|      return k > base && k + offset_size <= end && !(k & ((offset_size - 1) | (align - 1)));```

`k + offset_size <= end`

**Comment by mikkelfj** [comment] 2017-10-01 09:55
Background: The function affected checks headers which is field before the first element of an vector and related.
If you have a 8 byte sized vector, it might start at offset 12 where length is stored, and first element is at offset 16. But you cannot have length at offset 16 and first element at 20.

**Comment by mikkelfj** [comment] 2017-10-01 10:01
Does the error go away if you add 4 to the buffer size given to the verifier? Might be useful workaround for people running 0.4.3.

**Comment by AndrewJDR** [comment] 2017-10-01 10:19
I switched around some things on my project and now I'm having a hard time reproducing this :(

It's truly bizarre, as I was reproducing it consistently with no problems earlier, even after many repeated recompiles.

Apologies... I'll let you know if I can get it to come up again.

**Comment by mikkelfj** [comment] 2017-10-01 10:22
There certainly was something wrong, and I have just now pushed a new commit I'd like you to test. 

Added a new commit. The following is before the commit.

https://github.com/dvidelabs/flatcc/blob/7be25fa915cb86ceaedd943e1c84783563519be2/src/runtime/verifier.c#L138-L151


However, it is not very likely for the problem to surface as buffers and vectors need to be rather tiny. You might also be feeding buffers that are not allocated at an aligned address, or feeding 0 size as input to the verifier.

**Comment by mikkelfj** [comment] 2017-10-01 10:24
This is after the fix. https://github.com/dvidelabs/flatcc/blob/9d9e024f3e357034e46d4431a4f3bf94b7e8f13a/src/runtime/verifier.c#L138-L150

**Comment by mikkelfj** [comment] 2017-10-01 10:24
https://github.com/dvidelabs/flatcc/commit/9d9e024f3e357034e46d4431a4f3bf94b7e8f13a

**Comment by mikkelfj** [comment] 2017-10-01 10:37
To understand the snipper: k is the absolute memory address of the start of the vector. In the regression the length field were added to k, but one of the subsequent checks did not take this into account. So a buffer with a zero length vector placed at the end of the buffer could trigger the error.

Flatcc normally places vtables at the end which would safeguard against this, but a buffer created in javascript (as were the case be the reporter) would have vtables placed earlier in the buffer and therefore be subject to this regress.

Adding 4 padding bytes to the buffer and feeding a 4 bytes larger size to the verifier would likely work around the issue. This ONLY applies to flatcc v0.4.3 verification.

**Comment by mikkelfj** [comment] 2017-10-02 08:14
Closing, please reopen if there is new evidence after the latest commit.

**Comment by AndrewJDR** [comment] 2017-10-02 20:17
Will do, sorry for the lack of response. Against a deadline. Will get back to this later in the week.

**Comment by AndrewJDR** [comment] 2019-01-08 13:22
I think I'm running into this once again... or something very similar. The repro involves some private code so I'll probably just email it over to you...

**Comment by mikkelfj** [comment] 2019-01-08 14:18
Got the files, will have a look.

**Comment by mikkelfj** [comment] 2019-01-09 09:44
Closing again. It appears that the buffers in question were in fact incorrectly aligned - in part due to incorrect use of flatcc api calls with nested buffers, and in part due to buffers nested by other language implementations. This does not rule out possible bugs in the flatcc builder/verifier, but currently there is no evidence to suggest that.

**Closed by mikkelfj** 2019-01-09 09:44 UTC
Labels: bug
