### ISSUE TITLE
json printer garbage in 0.5.1-pre

### ISSUE THREAD

**Issue by jdall** [dvidelabs/flatcc#74] opened 2018-01-17 09:58 UTC
From time to time, I see garbage in generated json strings. This  issue appears to be present in both 0.4.3 (with the "JSON parser" and the "alligned_free" patches), 0.5.0 and 0.5.1-pre (commit ba9a8e6).

For testing, I'm sending the very same json string in a websocket request, that results in the very same json string for the response. Sometimes garbage is seen at the end of the json string.
When garbage is seen, the response is not sent - the write function of libwebsocket apparently don't like the garbage. 
So far, I've seen the garbage strings "pU" and "�U" .

From the test cycles I've executed, it appears that garbage is NEVER seen in the first response, but then it appears randomly.

Please find attached the fbs: [fbs.zip](https://github.com/dvidelabs/flatcc/files/1638447/fbs.zip)

Below is an example of an test cycle
```
JSON request:
{"msg_type":"GetLdvReq","msg":{"dvName":"Measurement_01"}}
JSON response:
{"msg_type":"GetLdvRsp","msg":{"st":{"code":0},"dv":
{"name":"Measurement_01","type":12,"value":"4.040000"}}}

JSON request:
{"msg_type":"GetLdvReq","msg":{"dvName":"Measurement_01"}}
JSON response:
{"msg_type":"GetLdvRsp","msg":{"st":{"code":0},"dv":
{"name":"Measurement_01","type":12,"value":"4.040000"}}}

JSON request:
{"msg_type":"GetLdvReq","msg":{"dvName":"Measurement_01"}}
JSON response:
{"msg_type":"GetLdvRsp","msg":{"st":{"code":0},"dv":
{"name":"Measurement_01","type":12,"value":"4.040000"}}}

JSON request:
{"msg_type":"GetLdvReq","msg":{"dvName":"Measurement_01"}}
JSON response:
{"msg_type":"GetLdvRsp","msg":{"st":{"code":0},"dv":
{"name":"Measurement_01","type":12,"value":"4.040000"}}}�U

JSON request:
{"msg_type":"GetLdvReq","msg":{"dvName":"Measurement_01"}}
JSON response:
{"msg_type":"GetLdvRsp","msg":{"st":{"code":0},"dv":
{"name":"Measurement_01","type":12,"value":"4.040000"}}}�U

JSON request:
{"msg_type":"GetLdvReq","msg":{"dvName":"Measurement_01"}}
JSON response:
{"msg_type":"GetLdvRsp","msg":{"st":{"code":0},"dv":
{"name":"Measurement_01","type":12,"value":"4.040000"}}}

JSON request:
{"msg_type":"GetLdvReq","msg":{"dvName":"Measurement_01"}}
JSON response:
{"msg_type":"GetLdvRsp","msg":{"st":{"code":0},"dv":
{"name":"Measurement_01","type":12,"value":"4.040000"}}}

JSON request:
{"msg_type":"GetLdvReq","msg":{"dvName":"Measurement_01"}}
JSON response:
{"msg_type":"GetLdvRsp","msg":{"st":{"code":0},"dv":
{"name":"Measurement_01","type":12,"value":"4.040000"}}}�U

JSON request:
{"msg_type":"GetLdvReq","msg":{"dvName":"Measurement_01"}}
JSON response:
{"msg_type":"GetLdvRsp","msg":{"st":{"code":0},"dv":
{"name":"Measurement_01","type":12,"value":"4.040000"}}}
```

**Comment by mikkelfj** [comment] 2018-01-17 10:18
I will have a look, but it is hard to tell without knowing the exact print method being used - some print to a dynamically growing memory buffer, some print to a file descriptor.

The commit you mention does include a fix that potentially overruns a buffer during printing, as you are probably aware of.

It could be a flushing issue since large buffers are not well tested, but then you have the issue with small buffers.

I suspect the issue has to due with initial allocation having zeroed memory and later this is not true, and somehow zero termination fails, or the end of buffer is slightly miscalculated before setting the termination.

The get_buffer method adds zero termination:

https://github.com/dvidelabs/flatcc/blob/ba9a8e6c599f333b6d516d2c4ceffcdb868ec11a/src/runtime/json_printer.c#L1217-L1224

Here is the printing code from test_json.c in which I have never seen such garbage. The test allocates a new buffer each time. If you are reusing the print buffer, that might be a hint as well.

https://github.com/dvidelabs/flatcc/blob/ba9a8e6c599f333b6d516d2c4ceffcdb868ec11a/test/json_test/test_json.c#L102-L110

**Comment by mikkelfj** [comment] 2018-01-17 10:23
FYI: you don't need the `attribute "priority";` it is just an example of how to define custom attributes so the schema parser does not get upset.

**Comment by jdall** [comment] 2018-01-17 10:35
Thanks, Mikkel.

Comparing your provided examples with my json printer, the code appear to be quite different. You know the API a lot better than I, so maybe you can tell what I've missed.

The function that generates the json string is as follows:
```
int json_toString (const char *fbbuf, size_t fbsize, char *jsonbuf, size_t jsize) {
  flatcc_json_printer_t ctx;
  int ret;

  flatcc_json_printer_init_buffer(&ctx, jsonbuf, jsize);
  modiccp_print_json(&ctx, fbbuf, fbsize);
  //flatcc_json_printer_flush(&ctx);
  if ((ret = flatcc_json_printer_get_error(&ctx))) {
    printf("could not print json to string\n");
  } 

  return ret;  
}
```
I'm calling it using:
```
            flatbuffer = flatcc_builder_finalize_aligned_buffer(&builder, &size);
            json_toString(flatbuffer, size, json, JSON_BUFFER_SZ);
```
JSON_BUFFER_SZ is 1024

Deallocation of buffers takes place at the end of the request handler:
```
    if (flatbuffer) {
      flatcc_builder_aligned_free(flatbuffer);
    }
    flatcc_builder_clear(&builder);
```

**Comment by mikkelfj** [comment] 2018-01-17 10:53
I recently changed the test code to be much more generic so I can test several different table types instead of just the generated root type printer. There is nothing wrong with a simpler approach.

I think the issue is that the buffer is not flushed fully similar to how printf works with stdout. With the function you are calling, it ought to happen automatically though.

The _as_root functions do call a print_last_nl macro, to terminate the json output with a newline if idented, but it only does a partial (efficient) flush.

https://github.com/dvidelabs/flatcc/blob/ba9a8e6c599f333b6d516d2c4ceffcdb868ec11a/src/runtime/json_printer.c#L130-L136

I'm not sure this is the correct way to fix it, or if it solves your problem, but could you try to fully flush the buffer either by uncommenting the line in your above dump, or by changing the last_nl macro to

```
/* Call at the end so print_end does not have to check for level. */
#define print_last_nl() do {                                                \
    if (ctx->indent && ctx->level == 0) {                                   \
        *ctx->p++ = '\n';                                                   \
    }                                                                       \
    flatcc_json_printer_flush(ctx);                                         \
} while (0)
```

**Comment by jdall** [comment] 2018-01-17 11:00
It appears that uncommenting the "flatcc_json_printer_flush(&ctx);" line solves the issue.

FYI, I also found that the issue can be fixed by adding a "  memset(jsonbuf, 0, jsize);" before the printer_init_buffer line.

Thank you very much for your help.

**Comment by mikkelfj** [comment] 2018-01-17 11:04
I think I have mostly tested with the dynamically growing print buffer. Here get_buffer sets a null terminator. I'm not sure the static buffer printer that you are using is doing that, but it probably should.

If you are sure that your output is limited to 1K, your approach is better than a dynamic printer buffer. The choice of print method is decided by the printer _init function called.

I'll look into the proper way of handling this.

**Comment by mikkelfj** [comment] 2018-01-17 12:18
The API is a bit clunky because it attempts to handle multiple different print output types with minimal abstractions. I think this can be improved, but it is not first on the list.

After looking into it some more, it is not the flush operation. If a fixed size buffer needs to flush, it is because it is full. Calling flush will actually raise an error because it indicates that the fixed buffer has run out of space.

The correct method to call is `flatcc_json_printer_get_buffer(ctx, *bufsiz)`
which will zero terminate, return the buffer, and it's size.

The apparent error is that the `flatcc_json_printer_table_as_root` which is called by the generated method `modiccp_print_json` does not call get_buffer internally, but just returns the length, or -1 on error. However, it is not always correct to call `get_buffer` because it depends on the kind of buffer that was initialized.

Therefore the user has to retrieve the returned length, check for error status, and set zero termination. Or call get_buffer on the printer context now that it is known to be a fixed size buffer.

This behavior can be improved, for example by remembering what buffer type was initialised, but then known output types must be hardcoded.

**Comment by jdall** [comment] 2018-01-17 12:59
Sorry, but it's not clear to me the changes I have to make to my json_toString function in order to adopt your proposed changes. Are you saying that I should not use the generated root printer at all?

**Comment by mikkelfj** [comment] 2018-01-17 13:46
> Are you saying that I should not use the generated root printer at all?

No, it should be fine. I havent worked with the printer for while, and the details weren't quite clear to me either. My previous explanation was not entirely solid.

I am working on a patch that should make your original code work, but it is a bit tricky to handle all use cases correctly.

**Comment by jdall** [comment] 2018-01-17 13:53
Ok. Thanks, Mikkel.

FYI, I actually found that calling flatcc_json_printer_flush sometimes results in an error, so I have chosen to do a memset on the json buffer before calling printer_init_buffer instead, as previously stated. 
That approach seems solid; at least it has yet to fail.

**Comment by mikkelfj** [comment] 2018-01-17 14:08
I think calling flatcc_json_printer_get_buffer(ctx, 0) after printing should get the same results, optionally give a pointer to a size argument.

I will publish a branch later today that should work without.

**Comment by jdall** [comment] 2018-01-17 14:23
Just to confirm that your suggestion to call flatcc_json_printer_get_buffer after printing seems to work ok.
For reference, the code is now:
```
int json_toString (const char *fbbuf, size_t fbsize, char *jsonbuf, size_t jsize) {
  flatcc_json_printer_t ctx;
  int ret;

  flatcc_json_printer_init_buffer(&ctx, jsonbuf, jsize);
  modiccp_print_json(&ctx, fbbuf, fbsize);
  flatcc_json_printer_get_buffer(&ctx, 0);
  if ((ret = flatcc_json_printer_get_error(&ctx))) {
    SLOGALWAYS0("could not print json to string");
  }
  return ret;
}
```

**Comment by mikkelfj** [comment] 2018-01-17 14:38
Thanks for confirming.
The patch is available here

https://github.com/dvidelabs/flatcc/tree/json-printer-flush

 You should be able to remove get_buffer with this - theoretically - my tests all call get_buffer.

Now the schema root printer and any  _as_root print call (except internal nested buffer op) and any flush or get_buffer call ensures that the internal buffer is zero terminated. For printing to streams, _as_root will flush the entire internal buffer automatically as opposed to partially flushing a convenient chunk size.

If you want to print error messages the above is a good starting point, but I suggest looking at test_json.c for detailed reporting. If you don't care about error codes you can also check for error with `0 > modicccp_print_json()`.

**Comment by mikkelfj** [comment] 2018-01-17 15:37
Could you please confirm if this works for you.In that case I will include it in upcoming 0.5.1.

**Comment by jdall** [comment] 2018-01-17 15:45
> Could you please confirm if this works for you.

Will do, later today...

**Comment by jdall** [comment] 2018-01-17 17:21
Your patch appears to be working!
The json_toString function has been reduced to:
```
int json_toString (const char *fbbuf, size_t fbsize, char *jsonbuf, size_t jsize) {
  flatcc_json_printer_t ctx;
  int ret;

  flatcc_json_printer_init_buffer(&ctx, jsonbuf, jsize);
  modiccp_print_json(&ctx, fbbuf, fbsize);
  if ((ret = flatcc_json_printer_get_error(&ctx))) {
    SLOGALWAYS0("could not print json to string");
  }
  return ret;
}
```
Thanks for providing the fix.

**Comment by mikkelfj** [comment] 2018-01-17 17:23
Great, thanks

**Comment by mikkelfj** [comment] 2018-01-17 17:24
Labelled bug, though strictly speaking it is not, since get_buffer was supposed to be called.

**Comment by mikkelfj** [comment] 2018-01-17 17:31
Merged to master

**Closed by mikkelfj** 2018-01-17 17:31 UTC
Labels: bug
