### ISSUE TITLE
Parsing JSON for struct with fixed size array

### ISSUE THREAD

**Issue by jrmarkle** [dvidelabs/flatcc#157] opened 2020-08-20 02:01 UTC
I'm having trouble getting JSON parsing to work for a struct with a fixed size array. I made an example with a very simple schema:
```
struct Vec3Fixed {
	x:[uint8:3];
}
```

Please see my example program: https://github.com/jrmarkle/flatcc/tree/json_test/test/json_fixed

It outputs
```
size 16
{"x":[12,34,56]}
mystruct_parse_json returned error: runtime error
parser.end:       0x562d23baf0d0
parser.error_loc: 0x562d23baf0d0
parser.line: 1
parser.pos: 17
```
so JSON printing looks fine but parsing is returning this "runtime error" pointing to the end of the buffer. Does anyone have an idea what's going here?

**Comment by jrmarkle** [comment] 2020-08-24 18:49
I've found that wrapping the `struct` in `table` works fine. Is this expected behaviour?

Commit without wrapper: https://github.com/jrmarkle/flatcc/commit/e219641fc434525dc5ee68903baa332550a3ec68
Commit with wrapper: https://github.com/jrmarkle/flatcc/commit/7958333155815b273ef3ea1b58b2818041c85456

**Comment by mikkelfj** [comment] 2020-08-24 23:07
Sorry I didn't get back before. It is supposed to work in both cases, but structs as root have a different code path that I might have missed. I'm not sure if you have made some mistakes in your code, but as far as I got yesterday, it looked OK, except you should use the builders free function in case you happen to link with different libraries.

However, Googles flatc tool now officially does not support structs as root whereas before documentation allowed it in principle but not in praxis. But I do think it is useful should be working in flatcc that we use here.

If you can spot the misbehaving code path, be my guest.

**Comment by jrmarkle** [comment] 2020-08-25 02:09
> However, Googles flatc tool now officially does not support structs as root whereas before documentation allowed it in principle but not in praxis. But I do think it is useful should be working in flatcc that we use here.

Ok, thanks for the info. I want my schemas to be compatible so I'll use tables as root.

**Comment by mikkelfj** [comment] 2020-08-31 10:25
OK, I have now debugged the problem. It is not related to fixed length arrays at all, but presumable any root struct parsed as JSON.

The reason for the problem is as follows: every sub-parser returns the buffer pointer following the fragment that it did parser, so the parent parser can proceed parsing from that point. All parsers must check that they do not read beyond the end of the buffer. If they do, they raise an error and return end of buffer. If a parser fails for any other reason, it also raises an error and returns end of buffer because this leads to a fast safe exit on error without every parser having to additionally check if an error was raised.

Any sub-parser that returns end of buffer always indicates an error because top-most parser must process a matching pair of { } brackets and a sub-parser therefore cannot reach the end without invalid JSON input.

However, the top-level parser can legally return end of buffer. Therefore the parse_as_root wrapper function must not treat a return value equal to end of buffer as an error. Instead it must check the parser error code that will be set if any parser failed during the parse. This works as intended. But, the root level struct parser calls an intermediate struct parser that fails to recognise this:

There are two parsers generated for structs: an inline parser used for tables, and a wrapper that handles structs outside of tables, which can be as part of a union, or as a standalone root. The standalone parser essentially just calls the inline version of the parser, after setting up the correct context, different from a table.

However, this goes wrong because the standalone struct parser assumes a parse error if the inline parser returns end of buffer. But that is not an error if the inline parser has consumed a root level struct. This is why it fails.

Note the `(buf == end)` test:

```
static const char *Vec3Fixed_parse_json_struct(flatcc_json_parser_t *ctx, const char *buf, const char *end, flatcc_builder_ref_t *result)
{
    void *pval;

    *result = 0;
    if (!(pval = flatcc_builder_start_struct(ctx->ctx, 3, 1))) goto failed;
    buf = Vec3Fixed_parse_json_struct_inline(ctx, buf, end, pval);
    if (buf == end || !(*result = flatcc_builder_end_struct(ctx->ctx))) goto failed;
    return buf;
failed:
    return flatcc_json_parser_set_error(ctx, buf, end, flatcc_json_parser_error_runtime);
}
```

The fix is to not test the end condition here because if the parser is not parsing at root level, either an error was already set, and there is no need to raise an error, or there will be a parent parser that will be missing a closing bracket and therefore raise an error.

The problem is sovled by changing the line 

` if (buf == end || !(*result = flatcc_builder_end_struct(ctx->ctx))) goto failed;`

into

`    if (ctx->error || !(*result = flatcc_builder_end_struct(ctx->ctx))) goto failed;`

I have add this to the master branch.

**Comment by mikkelfj** [comment] 2020-08-31 10:26
Can you please confirm that this also solves the problem at your end?
Although I am aware that you do want to use the table version for compatibility.

**Comment by mikkelfj** [comment] 2020-08-31 10:32
Fix is in commit cf9f1adbdea0ad8ea21d8683b37c166c2fde953e

**Comment by mikkelfj** [comment] 2020-08-31 10:36
Historical note: Presumably this error was introduced when unions were extended to also allowing for struct remembers, requiring, a change to the struct parser logic.

**Comment by jrmarkle** [comment] 2020-08-31 14:29
> Can you please confirm that this also solves the problem at your end?
> Although I am aware that you do want to use the table version for compatibility.

Confirmed. The version without a table now works after updating to the latest changes. 👍

**Comment by mikkelfj** [comment] 2020-08-31 14:30
Thanks

**Closed by mikkelfj** 2020-08-31 14:30 UTC
