### ISSUE TITLE
Doesn't compile with mingw32 gcc on windows with -std=c99

### ISSUE THREAD

**Issue by Elkantor** [dvidelabs/flatcc#173] opened 2020-12-29 11:00 UTC
On windows, when using gcc with the ming32 toolchain, it doesn't compile:

``` bash
make
[  6%] Built target flatccrt
[  7%] Building C object src/compiler/CMakeFiles/flatcc.dir/__/__/external/hash/cmetrohash64.c.obj
[  8%] Building C object src/compiler/CMakeFiles/flatcc.dir/__/__/external/hash/str_set.c.obj
[  9%] Building C object src/compiler/CMakeFiles/flatcc.dir/__/__/external/hash/ptr_set.c.obj
[ 10%] Building C object src/compiler/CMakeFiles/flatcc.dir/hash_tables/symbol_table.c.obj
In file included from D:\Projects\flatcc\src\compiler\hash_tables\symbol_table.c:2:0:
D:/Projects/flatcc/src/compiler/symbols.h:156:6: error: ISO C99 doesn't support unnamed structs/unions [-Werror=pedantic]
     };
      ^
cc1.exe: all warnings being treated as errors
make[2]: *** [src/compiler/CMakeFiles/flatcc.dir/hash_tables/symbol_table.c.obj] Erreur 1
make[1]: *** [src/compiler/CMakeFiles/flatcc.dir/all] Erreur 2
make: *** [all] Erreur 2
```

**Comment by mikkelfj** [comment] 2020-12-29 11:05
Have you looked at:
https://github.com/dvidelabs/flatcc/pull/171
There is ongoing work on updating the CMake system and also add GitHub actions compilation which includes a new mingw build cross and native.

I'm not claiming this solves your issue, since I don't recall fixing any unnamed unions. Maybe the mingw build only builds the runtime target?

FlatCC attempts to avoid unnamed unions because of portability issues so this likely needs to be fixed in the symbol table.

**Comment by Elkantor** [comment] 2020-12-29 13:23
Thanks for the link, I'll try by going on the branch of the PR to test if that fix the issue. Actually yeah, I guess the real fix should be to rewrite the structs which contain nested struct or unions ;)

**Comment by mikkelfj** [comment] 2020-12-29 14:50
You can see the mingw build here:

https://github.com/madebr/flatcc/runs/1596243638?check_suite_focus=true

Note that I had to make a few changes to flatcc before it would compile, but these are on the master branch now.

**Comment by mikkelfj** [comment] 2020-12-29 14:56
Also note the following comment in the pstdaligh.h header:

```
 * If stdalign.h is supported but heuristics in this file are
 * insufficient to detect this, try including <stdaligh.h> manually
 * or define HAVE_STDALIGN_H.
 ```

**Comment by mikkelfj** [comment] 2020-12-29 15:00
https://bellard.org/tcc/tcc-doc.html

> The keyword `__attribute__` is handled to specify variable or function attributes. The following attributes are supported:
aligned(n): align a variable or a structure field to n bytes (must be a power of two).

...

> The `__alignof__` keyword can be used as sizeof to get the alignment of a type or an expression.

**Comment by mikkelfj** [comment] 2020-12-29 15:09
Also note that there is a printf formatting issue that must be fixed in the CMakeList.txt file or whatever you use to build. A warning must be disabled. This has not been merged to master. You can find it in the PR discussion.

**Comment by mikkelfj** [comment] 2020-12-30 10:40
This union type `fb_value_t` is used everywhere, and the number of named indirections is already long when accessing values in the symbol table. So this is not an easy fix.

I suggest either removing -Wpedantic from the MinGW build, which should also fix MS formatting warnings, or use `-std=gnuc99`, or `-std=c11`, noting that c11 officially supports anonymous unions. If you do keep `-Wpedantic`, you need to add `-Wno-pedantic-ms-format` specifically for MinGW targets.

While I do want to support `-Wpendantic` wherever practically possible, it has also been disabled in FlatCC for the latest GCC versions because it became nearly impossible to silence an increasing flood of new warnings while maintaining portable code.

There is currently no MinGW detection in the CMakeList.txt but there is in a PR as mentioned earlier. Here `-std-c11` and `-Wno-pedantic-ms-format` is configured for MinGW.

**Comment by mikkelfj** [comment] 2020-12-30 10:41
Alternatively you can choose o build with FLATCC_RTONLY to limit the build to the runtime library. It should not depend on anonymous unions (hopefully).

**Comment by mikkelfj** [comment] 2023-10-24 18:44
Closing as won't fix. It is not practical to change the root cause, the anonymous union in fb_value and generally flatcc does not support pedantic warnings from gcc (as they work against portability). Following next release there will be some updates to the build system, and if there is explicit interest in mingw support, please add a PR for that with suitable flags.

**Closed by mikkelfj** 2023-10-24 18:44 UTC
Labels: wontfix
